### ISSUE TITLE
Fake Compilation on Windows 7

### ISSUE THREAD

**Issue by DQ318** [AmatCoder/mednaffe#101]
Hi, Everyone!

I am trying to compile the application on my Windows 7-64bits however, after following all guidelines and running the ".exe" file generated in the "src" folder, I get the following error: libgdk-3-0.dll was not found.

Strange because I have updated all GTK 3.12 packages. I use MSYS2 64bits.

Can anyone guide me on how to solve?
Thank you.

**Comment by AmatCoder** [comment]
Are you trying to compile master branch? Then you need:

- Copy mednafen emulator executable (and dlls) into the same folder than _mednaffe.exe_.
- Add your MinGW bin path (i.e. C:\msys64\mingw64\bin\) to Windows PATH.

**Comment by CrankySupertoon** [comment]
add C:\MinGW\bin\gcc to your PATH

**Comment by DQ318** [comment]
Thanks so much, it worked perfectly by adding MingW64 to my PATH.

However, I did the same procedure for a win32 and got the following error after compiling the application:

```
---------------------------
mednaffe.exe - Entry Point Not Found
---------------------------
Unable to find procedure entry point __divmoddi4 in libgcc_s_dw2-1.dll dynamic link library.
```
