### ISSUE TITLE
abandoned? (Not abandoned! yay!!!)

### ISSUE THREAD

**Issue by ghost** [AmatCoder/mednaffe#102]
Is this front end abandoned?

Just curious.

Currently a user of .88

**Comment by jjfmz42015** [comment]
Guess so :(

**Comment by AmatCoder** [comment]
Nope, development is just intermittent :)

Version 0.9 is almost ready but I am stuck with native theme on Windows.
Maybe it's better I make a release without it...

**Comment by jjfmz42015** [comment]
Awesome!!!! 

I dont see a downside of native theme. :)

**Comment by jjfmz42015** [comment]
anxious for version 9 lol

**Comment by AlanRibas** [comment]
Could you tell us what this new version will bring? Basically an early changelog.

**Comment by Kilowog01** [comment]
The last update was May 1, 2018, just update to 0.9. You can do it, @AmatCoder , I believe in you.

**Comment by MediaMaquina** [comment]
2 YEARS MAN. admit it lol

**Comment by RiedleroD** [comment]
rewrite started & abandoned, huh?

**Comment by anthonyajumelles** [comment]
@AmatCoder Open a GitHub Sponsor so we can keep you around and busy!

**Comment by AmatCoder** [comment]
Nah, I prefer to be freelance ;)
