### ISSUE TITLE
I can't configure 5 joysticks in Mednaffe.

### ISSUE THREAD

**Issue by AlanRibas** [AmatCoder/mednaffe#103]
First of all I would like to congratulate you on the excellent work you have done in building this frontend. It's the best I've ever tested.
I am experiencing the following problem. The video games "TurboGrafx" and "TruboGrafx CD" have the option of configuring 5 joysticks. But I know that the controls API called "Xinput" only supports 4 connected controls at a time. I think the only solution would be to use the API called "DirectInput" but I searched the Mednaffe frontend and I didn't find that option. Would it be possible to change individually from xinput to directinput depending on the system we want to emulate? Could you give me a suggestion to solve this problem?

thank you very much!!

**Comment by jjfmz42015** [comment]
Config once in emu. Press F1 for help

**Comment by AlanRibas** [comment]
> Config once in emu. Press F1 for help

I tried to configure both directly with the frontend and starting a game.
Xinput does not work with more than four controls. Only directinput does that. But I have no idea how to enable this directinput.

**Comment by jjfmz42015** [comment]
i use this method using 4 xbox controllers and one direct input controller

**Comment by AlanRibas** [comment]
> i use this method using 4 xbox controllers and one direct input controller

I thought about doing that.
The only problem with doing this is that I have no idea how to enable directinput in mednafen.
I already saw the option of choosing xinput or directinput in other emulators. But I don't see it on the Mednaffe frontend.

**Comment by jjfmz42015** [comment]
ill test and share config file later.

When I get a min at home.

**Comment by jjfmz42015** [comment]
I know that mednaffe is releasing .9 soon maybe will help?

Have you tried config via medlaunch maybe?


Ill be honest I didnt use a front end at all back when I set up my controls. This is why I think Ill just share my config file.

**Comment by AlanRibas** [comment]
> I know that mednaffe is releasing .9 soon maybe will help?
> 
> Have you tried config via medlaunch maybe?
> 
> Ill be honest I didnt use a front end at all back when I set up my controls. This is why I think Ill just share my config file.

I have no idea if the mednaffe developer aims to implement the possibility of choosing the joysticks API for mednafen-supported video games.
A problem copying your configuration would be losing all the settings I made for the other systems. If you can tell me how you did to configure the fifth control would be better. Thank you very much.

**Comment by AlanRibas** [comment]
> I know that mednaffe is releasing .9 soon maybe will help?
> 
> Have you tried config via medlaunch maybe?
> 
> Ill be honest I didnt use a front end at all back when I set up my controls. This is why I think Ill just share my config file.

I tried to configure it in two ways. The first was starting a game. The second was entering the mednaffe settings.
The problem is that mednaffen seems to use xinput by default. And if I can't change it, there's no way this emulator can recognize that a fifth joystick is connected. When I try to configure the fifth joystick in these two ways. When pressing the buttons nothing happens.

**Comment by AmatCoder** [comment]
> Would it be possible to change individually from xinput to directinput depending on the system we want to emulate?

Mednaffe can not choose the joysticks API because it must be the same that mednafen emulator uses.

> Could you give me a suggestion to solve this problem?

You can try with [XInput Plus](https://sites.google.com/site/0dd14lab/xinput-plus). It can be used as wrapper for DirectInput output.

**Comment by AlanRibas** [comment]
The problem is that I use mednafen along with a frontend called Gameex. I configure all emulators to work directly with Gameex. So I use mednaffe as a frontend to access mednafen resources. And I don't see how I could make everything work automatically through some kind of configuration.

My hope was that mednaffe could trigger some feature in mednafen so that depending on the system one wanted to emulate, the control API would be changed. But from what you told me that is not possible. The way is to forget the fifth player himself.
