### ISSUE TITLE
Strange keyboard button names in key assignment (global)

### ISSUE THREAD

**Issue by thesourcehim** [AmatCoder/mednaffe#104]
I see strange key names in global key assignment section, like "keyboard 99". They are actually correspond to real keys, but when I reassign them to exactly same keys, the names become proper (like "F1"). Linux version.
![mednaffe_keys](https://user-images.githubusercontent.com/4952491/66595758-45d10180-eba4-11e9-81be-3fc5a631baed.png)

**Comment by AmatCoder** [comment]
Are you using a version of mednafen emulator less than 1.21.0?
Or have you copied and pasted something from an old mednafen.cfg file?

Those keyboard mappings that snapshot is showing is how mednafen emulator handled them before 1.21.0.

**Comment by AmatCoder** [comment]
Nah, most likely you updated mednafen from an old version.
Quote from changelog (1.21.0):

> Configuration file is now named "mednafen.cfg" again, instead of "mednafen-09x.cfg";
>
> If "mednafen.cfg" doesn't exist or is for an old version (earlier than 0.9.0) of Mednafen, the settings will be loaded from "mednafen-09x.cfg" on startup, but still saved to "mednafen.cfg" on exit.
>
> Old input mappings will be translated internally, **except for keyboard mappings**, due to incompatibilities between how SDL 1.2 and 2 handle keyboards.
