### ISSUE TITLE
PSX cannot bind analog stick *and* d-pad

### ISSUE THREAD

**Issue by JulianGro** [AmatCoder/mednaffe#106]
I cannot find any option to get the left analog stick *and* the d-pad working in PSX.
The ui controller setup doesn't seem to have this option and Alt + Shift + 1 doesn't seem to work either.
This is a shame as this Dualshock 3 that I am using has native Linux support and works perfect otherwise.
This is on Mednaffe 0.8.8 with Mednafen 1.24.1

**Comment by AmatCoder** [comment]
About Mednafen emulator:

You can press **Ctrl + Shift + 1** until  the text **_"DualShock selected on port 1"_** is shown (or alternatively send _**"-psx.input.port1 dualshock"**_ option via command line).

Then you can configurate it with **Alt + Shift + 1**.

---
About Mednaffe frontend:

You must compile master branch to get support for all input devices.
Version 0.8.8 only support digital gamepad device (neither dualshock nor others analog devices).

**Comment by Ski-lleR** [comment]
I have the same problem, but with a One Controller.

I'm on Debian Sid, with xpad driver from kernel and Mednaffe from master.

My controller work everywhere (Native linux game, inside wine, other emulator) except mednaffe. Followed the documentation about "Remapping buttons and keys", specially the advice about use of Xbox Controller on *nix, but d-pad / lt / rt are not detected at all.

If you need screenshot, log or any other information i can provide.

**Comment by birdybro** [comment]
> 
> 
> About Mednafen emulator:
> 
> You can press **Ctrl + Shift + 1** until the text **_"DualShock selected on port 1"_** is shown (or alternatively send _**"-psx.input.port1 dualshock"**_ option via command line).
> 
> Then you can configurate it with **Alt + Shift + 1**.
> 
> About Mednaffe frontend:
> 
> You must compile master branch to get support for all input devices.
> Version 0.8.8 only support digital gamepad device (neither dualshock nor others analog devices).

Any special requirements on compiling the master branch? I'd like to compile it and am going to try to now, but didn't see any toolchain information. Can it just be done in Visual Studio, or is it kinda the basic build-essential in linux? I still am not at the level where I can just wing it and figure out all of the toolchain on my own to build from source for all software.

**Comment by AmatCoder** [comment]
Read this to compile mednaffe on Windows: [https://www.gtk.org/docs/installations/windows](https://www.gtk.org/docs/installations/windows)

I have used [MSYS2](https://www.msys2.org) successfully but if you prefer developing using Visual Studio, I guess you should use [gvsbuild](https://github.com/wingtk/gvsbuild) instead.

**Comment by AmatCoder** [comment]
Fixed in 0.9.0 version.
