### ISSUE TITLE
***ERROR***: Unrecognized argument: -nes.forcemono

### ISSUE THREAD

**Issue by CrasherX** [AmatCoder/mednaffe#107]
So I was tinkering with the settings and now, after touching "Force monophonic sound output", I am getting this error, unable to launch anything, no matter if the checkbox is checked or unchecked.

The problem persists even after uninstalling, deleting ~/.mednafen/ and reinstalling.

**Comment by AmatCoder** [comment]
Ouch! That option never existed in mednafen emulator... (NES machine only output mono sound.)

This bug is really old but is not present on master.

As workaround you can delete **~/.config/mednaffe.conf** file.

**Comment by CrasherX** [comment]
Ok, thanks.
