### ISSUE TITLE
Sega Saturn support doesn't work

### ISSUE THREAD

**Issue by papel** [AmatCoder/mednaffe#108]
This is the first time trying to play a Sega Saturn game. I'm trying to use mednaffe, but it has problems.

The first problem is that it uses invalid arguments. Maybe, it needs to be updated.
The second problem is that mednaffe thinks it's a PS1 game and I didn't find an option that tells to mednaffe that it's a Saturn game. 

This is the output that I get:

`"C:\shared\saturn\mednafen-1.24.3-win32\mednafen.exe" -ss.bios_na_eu "C:\shared\saturn\mednafen-1.24.3-win32\firmware\mpr-17933.bin" -ss.correct_aspect "1" -psx.dbg_level "0" "C:\shared\saturn\Magic Knight Rayearth (U).cue"`
`***ERROR***: Mednafen error: Unrecognized argument: -ss.bios_na_euEnd of execution caught.`

If I try running directly with bat and no arguments:
`"C:\shared\saturn\mednafen-1.24.3-win32\mednafen.exe" "C:\shared\saturn\Magic Knight Rayearth (U).cue"
`
It opens a mednafen window with a robotic-girl voice saying that the CD is supposed to be played on a Sega Saturn. I think it is the CD audio track that is played when it is inserted into a CD player.

The iso is correct and opens on Yabause (a buggy emulator).

**Comment by AmatCoder** [comment]
You are using 32-bit version of mednafen emulator.
This version does not include the Sega Saturn emulation (only 64-bit version does).

From [documentation](https://mednafen.github.io/documentation/ss.html):
> By default (and for the official releases for Windows), Saturn emulation is only compiled in for builds for some 64-bit architectures (x86_64, AArch64, PPC64).

**Comment by papel** [comment]
Too bad. :(
Even if it had a 32-bit version, it would be very slow here.

Thanks for the response.
