### ISSUE TITLE
Controller setup blacked out

### ISSUE THREAD

**Issue by victor03303** [AmatCoder/mednaffe#109]
I cannot configure my keyboard input :/
What goes wrong here?
![afbeelding](https://user-images.githubusercontent.com/55033363/83968642-ee1d9e00-a8ca-11ea-8579-4a37c3db2421.png)

**Comment by AmatCoder** [comment]
Mednafen emulator has been launched and it has not yet exited (or it became a zombie process).

**Comment by victor03303** [comment]
thank you for your replay
haven't had time yet to check for this

**Comment by victor03303** [comment]
> Mednafen emulator has been launched and it has not yet exited (or it became a zombie process).

that must have been it
thanks
