### ISSUE TITLE
Better "View>List>Show" Options

### ISSUE THREAD

**Issue by natbergu** [AmatCoder/mednaffe#110]
The options for filtering library results under View>List>Show are as follows:

1. All Files
2. Only zips
3. Only cue/toc/ccd/m3u

When emulating the TurboGrafx-16/PC-Engine and the CD addons with Mednafen, you will have some ROMs in .pce format (HuCards) and some in .bin/.cue format (CDs). With the way this filter currently works, it isn't possible for you to see both the .pce and the .cue files without either cluttering up your list with dozens of .bin tracks or zipping all of your files (not ideal for the CD games).

Maybe we could have an option where we could choose what extensions we want to show/hide? That would certainly make it easier to fine-tune the already great library functionality of Mednaffe.

**Comment by AmatCoder** [comment]
This has already been implemented in master:

![mednaffe-0.9.0](https://cloud.githubusercontent.com/assets/3890995/23666966/57f5d556-0354-11e7-8453-184746393477.png)

The option _**Comma-separated list of filetypes to show**_ allows it in a _per-folder_ basis (in your case: "pce,cue").

**Comment by natbergu** [comment]
Oh! Sorry for wasting your time then. I look forward to seeing this in the next release!
