### ISSUE TITLE
[Ubuntu Buddie]  -nes.forcemono issue

### ISSUE THREAD

**Issue by blueskup** [AmatCoder/mednaffe#112]
When start the game ROOM any, after click at some config and made purge and installed several times, no cue why stopped playing NES Games.

Check log:

`Executing mednafen with command line: 
"/usr/games/mednafen -psx.dbg_level 0 -snes.shader goat -nes.shader none -snes.tblur 0 -nes.stretch 0 -snes.shader.goat.fprog 1 -video.driver opengl -nes.sound_rate_error 0,000040 -nes.tblur 0 -nes.pal 1 -ngp.stretch aspect_int -nes.soundq 3 -nes.special none -ngp.shader.goat.pat slenderman -sound 1 -snes.tblur.accum 0 -snes.tblur.accum.amount 49 -lynx.lowpass 1 -ngp.special super2xsai -nes.ntscblitter 0 -nes.n106bs 1 -ngp.shader.goat.fprog 1 -snes.stretch full -nes.gg 1 -pce.stretch 0 -snes.forcemono 0 -nes.fnscan 1 -video.frameskip 1 -cheats 1 -snes.h_blend 0 -snes.special none -pce.forcesgx 0 -nes.shader.goat.slen 0 -snes.videoip x -nes.nofs 1 -snes.correct_aspect 0 -video.glvsync 1 -nes.shader.goat.pat slenderman -ngp.scanlines 30 -ngp.shader goat -video.fs 1 -snes.shader.goat.slen 0 -autosave 1 -nes.correct_aspect 0 -snes.shader.goat.pat borg -sound.driver alsa -video.blit_timesync 1 -nes.forcemono 0 /home/n10/Downloads/NES GAMES Nintendinho/DONKEY_KONG_COUNTRY.SMC "
----
Starting Mednafen 0.9.48
 Build information:
   Compiled with gcc 7.2.0
   Compiled against zlib 1.2.11, running with zlib 1.2.11(flags=0x00000055)
   Compiled against SDL 1.2.15, running with SDL 1.2.15
   Running with libsndfile-1.0.28
 Base directory: /home/n10/.mednafen
 Emulation modules: nes snes gb gba pce lynx md pcfx ngp psx ssfplay vb wswan sms gg snes_faust pce_fast demo cdplay
 Loading settings from "/home/n10/.mednafen/mednafen-09x.cfg"...
  Loaded 3338 valid settings and 0 unknown settings.
Unrecognized argument: -nes.forcemono
----
End of execution caught.
`

**Comment by AmatCoder** [comment]
Same as issue #107.

This bug is fixed on master.
As workaround you can delete **~/.config/mednaffe.conf** file (or just remove the line containing _-nes.forcemono_).
