### ISSUE TITLE
Cannot assign HOME/GUIDE button from a Xinput device

### ISSUE THREAD

**Issue by vico93** [AmatCoder/mednaffe#113]
I'm currently using a Dualshock 4 as a xinput device (via [DS4Windows](https://github.com/Ryochan7/DS4Windows) 2.2.2), and i'm not being able to assign the PS/HOME button to PSx analog button toggle. I can do it directly in mednafen (using the built-in controller config), but not in mednaffe. Also in other emulators i can assign that key as well.

The item i'm trying to bind:
![image](https://user-images.githubusercontent.com/3485505/106315140-9660e800-6249-11eb-8b5f-1ed2e9595df0.png)

The PS Button:
![image](https://user-images.githubusercontent.com/3485505/106315207-b0022f80-6249-11eb-8440-7efc70aca080.png)

The GUIDE (aka HOME) button on a x360 controller:
![image](https://user-images.githubusercontent.com/3485505/106315479-0bccb880-624a-11eb-8067-b4c708daf4c2.png)

**Comment by AmatCoder** [comment]
Yes, mednafen emulator uses **XInputGetStateEx** which is an undocumented function that is required to get the state of the guide button.

I will try to implement this but I am not sure if I can test it properly.

**Comment by AmatCoder** [comment]
Fixed with commit f9de470 (included in [0.9.1](https://github.com/AmatCoder/mednaffe/releases/tag/0.9.1) release).

Note:
This needs **xinput1_3.dll** or **xinput1_4.dll** libraries.
**XInputGetStateEx** is not available with **xinput9_1_0.dll** library (it ships with Vista and Windows 7).
