### ISSUE TITLE
minimize, close, full screen buttons look wrong windows 7

### ISSUE THREAD

**Issue by MediaMaquina** [AmatCoder/mednaffe#114]
I think this is a bug. If it isn't then i don't know why they all look the same...
version 0.9

win7 theme in win7
![win7](https://user-images.githubusercontent.com/8179611/106390555-3739d980-63e9-11eb-8b2c-79dbfc119b43.png)

win10 theme in win7

![win10](https://user-images.githubusercontent.com/8179611/106390561-3b65f700-63e9-11eb-81da-9cbda54fa3cc.png)

**Comment by AmatCoder** [comment]
Yes, it is a bug.
For some reason I can't replicate this on Windows 7, but I can on Windows 10.
Anyway, this will be fixed in the next version.

**Comment by AmatCoder** [comment]
Fixed with 0.9.1 release.
