### ISSUE TITLE
Turbo buttons support

### ISSUE THREAD

**Issue by KOT040188** [AmatCoder/mednaffe#116]
How about turbo button support. As a kid, I played on dandy and smd consoles and had buttons like this on their gamepads. Now, without them, playing games is extremely inconvenient.

**Comment by AmatCoder** [comment]
If turbo buttons were a kind of auto-fire buttons, you can use  **'Rapid Button A'** & **'Rapid Button B'** ones.

If not, you would have to suggest its implementation to mednafen authors.
