### ISSUE TITLE
Network client interface in mednaffe

### ISSUE THREAD

**Issue by Andrey20111987** [AmatCoder/mednaffe#118]
Open Kaillera - n02_2014 v0.5r3 (kaillera 0.9 compatible) - Feb 19 2014

Could you modify the emulator so that the kaillera 0.9 interface could be used on the network to select servers and connect to games?
![Screenshot_136](https://user-images.githubusercontent.com/17760525/112550477-7de7f680-8dd0-11eb-971c-90568b7ea1e9.png)

**Comment by Andrey20111987** [comment]
![image](https://user-images.githubusercontent.com/17760525/112550971-3dd54380-8dd1-11eb-99cb-d8ec59feeb67.png)
The main problem is that the user does not see the lobby in the kaillera 0.9 client.
Proposal to use the development of kaillera 0.9 client

**Comment by Andrey20111987** [comment]
https://github.com/eisenbe7/KailleraNet

**Comment by Andrey20111987** [comment]
At the moment. In the network game of midnafina there is no interface, which is in the killer's server.
This is a list of the servers, the number and the number of players on them,
Server lobby with a list of players, games, chat lobby.

**Comment by Andrey20111987** [comment]
![image](https://user-images.githubusercontent.com/17760525/112892428-f822be80-90e1-11eb-982e-bf33371c4e04.png)

**Comment by AmatCoder** [comment]
Kaillera is not supported by mednafen emulator.
