### ISSUE TITLE
Typo in playstation input screen

### ISSUE THREAD

**Issue by coldshouldermedia** [AmatCoder/mednaffe#119]
Wrong button description is listed. 

![73ClXySvWn](https://user-images.githubusercontent.com/54368516/114247399-3de94d80-9952-11eb-9f3b-fde88d168c0d.png)

**Comment by AmatCoder** [comment]
Nice catch!
Thanks for reporting.

**Comment by AmatCoder** [comment]
Fixed with released version [0.9.2](https://github.com/AmatCoder/mednaffe/releases/latest)
