### ISSUE TITLE
Allow larger fonts for game list please?  -feature request

### ISSUE THREAD

**Issue by Eggo-dotcom** [AmatCoder/mednaffe#123]
Allow larger fonts for game list please?  -feature request

Like the ability for user to set font size?

**Comment by AmatCoder** [comment]
Windows or Linux?

And why just the game list?  It uses the same size as the rest of the application (and the entire system).

**Comment by Eggo-dotcom** [comment]
Windows and cause i use it on my gaming pc which is in my living room on a 65” 12 ft away I would like to increase if possible is all. If I increase entire system other apps break. Maybe a dumb request i dont know

**Comment by AmatCoder** [comment]
No, that makes sense.

**Comment by AmatCoder** [comment]
Implemented on version [0.9.2](https://github.com/AmatCoder/mednaffe/releases/latest)
