### ISSUE TITLE
packaging problem?

### ISSUE THREAD

**Issue by sillyspiel** [AmatCoder/mednaffe#124]
After upgrading to Linux Mint 20 today (Ubuntu 20.04 base) I noticed that the repositories contain the 1.xx.x series of mednafen (1.22.2 to be precise) whereas the version of mednaffe that is packaged is the old 0.8.8-1 version. I noticed with these installed that changing things in mednaffe's settings didn't seem to be reflected in mednafen's config file. So I uninstalled the version of mednaffe installed from the repos and instead installed the latest version from source.
Does this sound right? Could this create other problems for users?

**Comment by AmatCoder** [comment]
There should be no problems with that.

But there shouldn't be a problem with these versions from repositories either.
Keep in mind that mednaffe does not change mednafen's config file until a game is launched.
Also configuration file is now named "mednafen.cfg", instead of "mednafen-09x.cfg".

**Comment by sillyspiel** [comment]
I know that, but yet the problem was still there. Normally, changing mednafen's config file manually would be reflected in Mednaffe. But it wasn't.
 Ah well, got the new version anyways and things now work as expected.

-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


May 14, 2021, 6:36 p.m. by ***@***.***:

**Comment by AmatCoder** [comment]
Then I close this.
