### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by Mechanical-sanity** [AmatCoder/mednaffe#128]
Will this gui have a dark mode? Right now, it is burning my eyes

**Comment by AmatCoder** [comment]
I assume you're using Windows.

**_Adwaita_** and **_Windows10_** themes include dark modes, just they are not exposed to the GUI.
This will be implemented in the next version. 

But right now you can see the dark modes via command line:

1. Open cmd.exe
2. Write: `set GTK_THEME=Windows10:dark` or `set GTK_THEME=Adwaita:dark`
3. Execute mednaffe within this cmd session: `C:\yourpath\mednaffe.exe`

**Comment by AmatCoder** [comment]
Implemented on version [0.9.2](https://github.com/AmatCoder/mednaffe/releases/latest)
