### ISSUE TITLE
Cannot find mednafen.cfg inside bin/ or lib/ folders on Windows

### ISSUE THREAD

**Issue by mayawarrier** [AmatCoder/mednaffe#129]
If mednaffe.exe is located in a directory whose path contains "bin" or "lib", mednafen.cfg cannot be found (even if in the same folder as mednaffe.exe).

For eg.
if the path for mednaffe.exe is D:\bin\mednaffe\mednaffe.exe
and the path for mednafen.cfg is D:\bin\mednaffe\mednafen.cfg,
(same directory)
mednafen.cfg will still not be found. This is true for "lib" as well.

**Comment by AmatCoder** [comment]
Bug confirmed. It is even [documented](https://developer.gnome.org/glib/stable/glib-Windows-Compatibility-Functions.html#g-win32-get-package-installation-directory-of-module). Just lack of attention on my part.
