### ISSUE TITLE
"Recent files" feature

### ISSUE THREAD

**Issue by xmypoeytpo** [AmatCoder/mednaffe#131]
Hello, 
I would like to see the "recent files" feature. Almost all emulators have this feature. I am also looking forward to 7zip archives support. And this is even more important than the "recent files" support. All of my roms stored in the archives. It is very inconvenient to keep them unpacked.

**Comment by AmatCoder** [comment]
"Recent files" feature could be implemented, thanks for suggestion.

But 7zip support is unlikely because mednafen emulator does not support it.

**Comment by xmypoeytpo** [comment]
Mednafen shouldn't support it . I mean multi rom archives. You have already this issue [#4 ](https://github.com/AmatCoder/mednaffe/issues/4). For example, MedGui Reborn, Nestopia, FCEUX support it. One archive can include up to 10-15 different roms. Such as Japanese, American version, various hacks and translations. If you unpack all this, you get a huge number of files.

**Comment by nathanzachary** [comment]
I, too, would really like to see a "Recent games" list as it can be a bit cumbersome to scroll through lists of thousands of titles.  A possible method of implementing would be to look in $HOME/.mednafen/sav/ for save states and sort them by atime or mtime.

**Comment by AmatCoder** [comment]
Fixed with version [0.9.3](https://github.com/AmatCoder/mednaffe/releases/tag/0.9.3).

**Comment by nathanzachary** [comment]
Thank you very much for implementing the "Open Recent" sub-menu; it's really helpful!
