### ISSUE TITLE
Make a "show only .cue in game list" option like in the old versions of mednaffe

### ISSUE THREAD

**Issue by ForeskinJohn** [AmatCoder/mednaffe#133]
this option would be handy to cleanup the interface for folks who dont have their bin's & cue's zipped up.

**Comment by AmatCoder** [comment]
Now you can set filters per folder to show only files with those extensions:

Edit -> Manage Folders -> Setup -> Space-separated filters

![mednaffe_filter](https://user-images.githubusercontent.com/3890995/141133624-cba16310-4b7d-4843-bebf-efdffd8ee2ca.png)


![mednaffe_filter2](https://user-images.githubusercontent.com/3890995/141135360-35037d65-edad-4259-8577-4b85a72b7808.png)

**Comment by ForeskinJohn** [comment]
thanks for clearing this up for me
