### ISSUE TITLE
Pce setting missing correct aspect ratio option

### ISSUE THREAD

**Issue by Eggo-dotcom** [AmatCoder/mednaffe#136]
Pce setting missing correct aspect ratio option

**Comment by AmatCoder** [comment]
Yes, option is missing with **pce_fast** emulation module.
The **pce** module has no such option.

**Comment by Eggo-dotcom** [comment]
> Yes, option is missing with **pce_fast** emulation module.
> The **pce** module has no such option.

Yes, possibly add to next release?

**Comment by AmatCoder** [comment]
The **pce_fast** correct aspect ratio option will be in the next release.

**Comment by Eggo-dotcom** [comment]
also shows in your test build you shared with me.

thanks
