### ISSUE TITLE
Screenshots not working. 

### ISSUE THREAD

**Issue by Eggo-dotcom** [AmatCoder/mednaffe#137]
Screenshots not working. 

Had to find hidden screenshot area and expand but still not working. What format must it be?

**Comment by Eggo-dotcom** [comment]
So did .png and named same as rom

doesnt work

windows 10

using 0.92

**Comment by Eggo-dotcom** [comment]
Anyone else have this issue?

**Comment by AmatCoder** [comment]
How did you do .png?

**Comment by Eggo-dotcom** [comment]
> How did you do .png?

Screen shot via mednafen, then renamed according. With my old install if mednaffe this had worked.

i have trouble getting the preview to show up on this new one and even though i can get the area to show up the pictures wont. New computer fresh install on fresh windows 10 pro 21h1

**Comment by Eggo-dotcom** [comment]
Please ignore. I was messing up. I had path for snaps set under global but not path under folder setup, the bug was me lol sorry and thank you
