### ISSUE TITLE
PCE autofire entry missing

### ISSUE THREAD

**Issue by ghost** [AmatCoder/mednaffe#141]
PCE/TG16 auto fire entry missing (retail tg16 have autofire) some games need it

**Comment by Eggo-dotcom** [comment]
seems rapid fire is only missing on this system (this system has software written for use with autofire)

current walk around is map via mednafen

**Comment by AmatCoder** [comment]
Confirmed, rapid input is missing on **pce** and **pce_fast** modules.
Thanks for reporting.

**Comment by Eggo-dotcom** [comment]
Thanks for reading.

**Comment by Eggo-dotcom** [comment]
i see you added already. anywhere to download devbuilds?

**Comment by AmatCoder** [comment]
I uploaded last windows build here: https://ufile.io/day5i6pe

**Comment by Eggo-dotcom** [comment]
> I uploaded last windows build here: https://ufile.io/day5i6pe

Thank you!!

**Comment by Eggo-dotcom** [comment]
Works great!

**Comment by Eggo-dotcom** [comment]
maybe release this build for all to see? these updates were a must for anyone with boxart and or using pce

**Comment by Shinobi-1987** [comment]
Ghost is me, new account,still using this build, only thing i see it really needing is the ability to specify path for mednafen due to a bug i noticed whe placing a shortcut on a windows 10 desktop if stored on a secondary hdd.

**Comment by Shinobi-1987** [comment]
Maybe release this fix build?

**Comment by Shinobi-1987** [comment]
> > I uploaded last windows build here: https://ufile.io/day5i6pe
> 
> Thank you!!
> 
> will test today

Works amazing but download link expired for others

**Comment by AmatCoder** [comment]
Fixed with version [0.9.3](https://github.com/AmatCoder/mednaffe/releases/tag/0.9.3).
