### ISSUE TITLE
this is missing on tg-16/pce where it is essential

### ISSUE THREAD

**Issue by Eggo-dotcom** [AmatCoder/mednaffe#142]
this is missing on tg-16/pce where it is essential

_Originally posted by @Eggo-dotcom in https://github.com/AmatCoder/mednaffe/issues/47#issuecomment-1022436269_

**Comment by Eggo-dotcom** [comment]
;pce, Port 1, Gamepad: Rapid I
pce.input.port1.gamepad.rapid_i keyboard 0x0 22

;pce, Port 1, Gamepad: Rapid II
pce.input.port1.gamepad.rapid_ii keyboard 0x0 7

**Comment by AmatCoder** [comment]
Same as #141, I guess.
