### ISSUE TITLE
user mode (feature idea/request)

### ISSUE THREAD

**Issue by ghost** [AmatCoder/mednaffe#144]
So running the latest build you shared I find this perfect!

ONe thing I would wish for would be the ability to lock it once all is set up, ie: a user only mode.

Once user mode is activated settings can not be accidentally changed in front end.

Helpful for those who have little kids accessing the front end.

(Again just an idea that would be a cool nice feature for some)

I am loving this front end. 

Its clean and does all I would want!

**Comment by AmatCoder** [comment]
Thanks for idea but this will not be implemented.

In general, it is preferred to make a backup of configuration files or to use file access control / permissions from operating system.
