### ISSUE TITLE
No audio with Pipewire

### ISSUE THREAD

**Issue by poopingpenis** [AmatCoder/mednaffe#145]
I'm using Pipewire on Gentoo compiled with pipewire-alsa, and choosing alsa on Mednaffe and opening a game says it can't find an audio device. However, running mednafen directly with -sound.device sexyal-literal-default works just fine.

**Comment by AmatCoder** [comment]
It is documented [here](https://mednafen.github.io/documentation/#Section_troubleshooting_nosoundlinux):

> Due to historical Linux distribution design decisions and problems with various software audio mixing solutions on Linux, Mednafen's ALSA output code attempts to output to device "hw:0" by default. This may cause problems if your sound card does not support hardware mixing of streams and your system is running another program that is monopolizing the sound device (like the PulseAudio server), or you have used multiple sound cards.
> 
> For the case of PulseAudio, you can utilize the [pasuspender](http://linux.die.net/man/1/pasuspender) tool, or set the [sound.device](https://mednafen.github.io/documentation/#sound.device) setting to "sexyal-literal-default" to try to use PulseAudio through ALSA (assuming your distribution has things configured properly); the use of pasuspender is the recommended option.

It says PulseAudio but it also is applicable to PipeWire.
