### ISSUE TITLE
"syscard3.pce" expected checksum is incorrect

### ISSUE THREAD

**Issue by SamRohod** [AmatCoder/mednaffe#148]
The MD5 of the correct "syscard3.pce" file is (from [HERE](https://docs.libretro.com/library/beetle_sgx/)): 38179df8f4ac870017db21ebcbf53114
which has SHA-256 value: E11527B3B96CE112A037138988CA72FD117A6B0779C2480D9E03EAEBECE3D9CE

the expected value in Mednaffe is different.

**Comment by AmatCoder** [comment]
Yes, it seems that **syscard3.pce** file from Mednaffe has padding zeros at beginning so I'm afraid you're right.

I don't know why I jumped to the conclusion that it was correct. Let's me ask about this on IRC.

Thanks for reporting this and sorry for late reply!

**Comment by AmatCoder** [comment]
Fixed with version [0.9.3](https://github.com/AmatCoder/mednaffe/releases/tag/0.9.3).

Thanks for the report!
