### ISSUE TITLE
Allow passing ROM as parameter on the Flatpak version?

### ISSUE THREAD

**Issue by Viktini** [AmatCoder/mednaffe#150]
I've been trying to set up some of my libraries on my Steam Deck and it'd be nice if Mednaffe, or at least the Flatpak version, can simply be passed a ROM file as a parameter that can skip the UI and go to Mednafen directly. This would work for frontends like EmulationStation which can directly load emulators in an organised UI, or utilities like Steam ROM Manager that lets you load it directly from Steam.

Since Mednaffe is the only easy way to install Mednafen on SteamOS 3, I thought I'd suggest the idea. Though if the option is there already, I'm not sure on how to access it.

**Comment by AmatCoder** [comment]
With Flatpak version you can access to mednafen executable directly.

Not sure about SteamOS but on Arch Linux you can run it like this:

System-wide installed:
`$ /var/lib/flatpak/app/com.github.AmatCoder.mednaffe/current/active/files/bin/mednafen    /path/to/your/rom.zip`

Or if per-user installed:
`$ ~/.local/share/flatpak/app/com.github.AmatCoder.mednaffe/current/active/files/bin/mednafen    /path/to/your/rom.zip`

**Comment by Viktini** [comment]
That does it. Thank you!

**Comment by harvii** [comment]
I'm also trying to run Mednafen directly but I keep getting an error complaining that libFLAC.so.8 is not found; any idea why this might be?
