### ISSUE TITLE
Hide the .bin/.iso from the game list

### ISSUE THREAD

**Issue by SailorVickFGC** [AmatCoder/mednaffe#154]
Hey o/
I'm an admin for some Fighting Games & there's one thing that trouble a lot of newcomers: they click on .bin and get an error.
It causes a lot of misunderstandings, they think they can't play or have deeper emulator problems... when they just need to click on .cue.
I don't think there's a scenario where you want to click on them anyway?

Would it be possible to hide the .bin/.iso by default?
- Stop people from clicking on .bin/.iso and panicking from the error message. 
- Make the game list more readable too (some games have all the tracks as separate .bin).

Thanks in advance ^^

**Comment by AmatCoder** [comment]
> [...] they click on .bin and get an error. It causes a lot of misunderstandings, they think they can't play or have deeper emulator problems... when they just need to click on .cue.

With the latest versions of mednafen emulator gives this error (for me it is clear enough):
```
Mednafen error:
  Error loading "disc.bin": maximum allowed size of 67108864 bytes exceeded.
  If you are trying to load a CD image, load it via CUE/CCD/TOC/M3U instead of BIN/ISO/IMG.
```


> I don't think there's a scenario where you want to click on them anyway?

Some systems can use .bin files (such as Megadrive).


> Make the game list more readable too (some games have all the tracks as separate .bin).

You can set filters per folder to show only files with some extensions (cue, m3u):
Edit -> Manage Folders -> Setup -> Space-separated filter


![image](https://user-images.githubusercontent.com/3890995/141135360-35037d65-edad-4259-8577-4b85a72b7808.png)

**Comment by VickGE** [comment]
> With the latest versions of mednafen emulator gives this error (for me it is clear enough):

While I agree, a lot of people are also aren't tech savvy and just see an error: panic, don't read it & just close it.
Some try to use the zip file as a rom & some panic when I tell then to press "t" to open a console... 
In the past 3 years I got to understand some people are really not used to playing on PC & to emulation (that aren't like fightcade by example).

> You can set filters per folder to show only files with some extensions (cue, m3u):
> Edit -> Manage Folders -> Setup -> Space-separated filter

I didn't know about that! Maybe I can use that in the preset in the zip file I give, so people don't get confused.
I still think it would be nice to have that ON by default imo.

And for Megadrive I dunno if there's something to differentiate them & show them by default too?
like a .bin without .cue or something? ¯\_(ツ)_/¯
