### ISSUE TITLE
Virtual Boy: Add the 2D viewing modes present in the current version of Mednafen

### ISSUE THREAD

**Issue by ArhumMK** [AmatCoder/mednaffe#155]
In the Current stable version of Mednafen, `left` and `right` modes have been added for `vb.3dmode` . Which allows for viewing either one of the two screens at a time, allowing games to be played in 2D. Please update these options into mednaffe, thanks!

P.S. How does one add cover art/screenshots to a game in the game list?

**Comment by AmatCoder** [comment]
Fixed with version [0.9.3](https://github.com/AmatCoder/mednaffe/releases/tag/0.9.3).
