### ISSUE TITLE
Can't change key maps / controls from GUI while game is running

### ISSUE THREAD

**Issue by absolutelynothinghere** [AmatCoder/mednaffe#159]
Sometimes I'm in the middle of a game and wish to change the mapping for one or two keys, but unfortunately I can't change the mappings at all from the GUI once a game is launched. I often just resort to closing the game, re-mapping the keys I want, then re-launching. That can get quite cumbersome... Thanks.

**Comment by AmatCoder** [comment]
This is not possible.
Mednaffe uses command-line invocation so options only can be changed when launching.
