### ISSUE TITLE
There is no "Never hide mouse cursor" checkbox in Mednaffe settings

### ISSUE THREAD

**Issue by ghost** [AmatCoder/mednaffe#160]
In MedGui Reborn window => Config button => Video tab, there is a Mouse Cursor drop down list where the user can choose whether or not the mouse cursor is visible or hidden while playing any game or rom.

I tried to find something similar with Mednaffe but I didn't find it.

Please add a "Never hide mouse cursor" checkbox to Mednaffe settings.

Mednafen can show the mouse cursor when running it with the right commandline option and MedGui Reborn proves it.

I hate that the mouse cursor becomes invisible every time it is inside the client area of the game window.

I am playing games in a window, not fullscreen. I don't like fullscreen at all.

WARNING

While I don't see any "Never hide mouse cursor" checkbox in Madnaffe settings I am using MedGui Reborn instead of Mednaffe!

**Comment by AmatCoder** [comment]
Fixed with version [0.9.3](https://github.com/AmatCoder/mednaffe/releases/tag/0.9.3).
