### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by ghost** [AmatCoder/mednaffe#166]
Dead?

**Comment by adviseore** [comment]
> Dead?

Still alive and doing everything I expect from it? does it need an update? Maybe an easier gui for netplay implemented could help. You do understand mednafen is the backbone of this software?

**Comment by LivingDaylights** [comment]
Options like rapid fire mapping for pce 2 button controllers missing.


The gui itself has issues under windows 10 and 11 but its been long since the last release so i asked

**Comment by AmatCoder** [comment]
Not dead but I don't have time for this (and others fun projects) lately, sorry. :(
