### ISSUE TITLE
add new frontend bundled latest cores for Android phone

### ISSUE THREAD

**Issue by soundsnow** [AmatCoder/mednaffe#168]
like jzIntvImGui for jzintv - an Intellivision emulator frontend
https://github.com/jenergy/jzIntvImGui
Contains Windows, Linux and Android versions
Lock portrait or landscape
PinePhone is Linux phone, but most people prefer Android phone
why submit this issue(request)?
issue 151 and PR 152
any plans to port it to Android in the future?

**Comment by AmatCoder** [comment]
> [...] any plans to port it to Android in the future?

Nope, sorry.
