### ISSUE TITLE
Xinput doesn't work

### ISSUE THREAD

**Issue by Papermanzero** [AmatCoder/mednaffe#17]
Setup a mednaffe instance and assign several buttons to the xbox360 controller.
It seems the mapping in mednaffe is working without any issue (expect that there is no deadzone for the joysticks). However if the user starts a game, the controller inputs are not recognized by the game.
Mean you cannot play the game. 
If a keyboard is used to assign buttons, it is working without any issues.

**Comment by AmatCoder** [comment]
Xinput support was developed a few weeks ago but laziness prevented me to upload code to github...;) 
In the next few days I will do.

**Comment by Papermanzero** [comment]
That's great! Mednaffe is clearly the most advanced and best graphical user interface for Mednafen. :)
Thanks for the work.

**Comment by AmatCoder** [comment]
Fixed on a15ad389ffd5c4d2d8aa2ded78c2691404fd108a commit.
