### ISSUE TITLE
sega genesis controller input

### ISSUE THREAD

**Issue by adviseore** [AmatCoder/mednaffe#171]
I am very confused because for Port 1 it only has button A and B and no C? but for Port 2 A,B,C is available. Also is 6 buttons available for genesis? really curious about this, any help appreciated, thank you.

**Comment by adviseore** [comment]
Sorry I diid not clarify this is in reference to the sega genesis console

**Comment by jeandestouches** [comment]
Hi,

Sega Genesis/Megadrive -> Input

Global | Port 1 | Port 2

Input device:
none
gamepad
gamepad2
gamepad6
megamouse

Select the port, then under "Input device", you can choose which type of gamepad you want to configure. 2/3/6 buttons or megamouse.
You most likely have gamepad2 set up for Port1, change it to gamepad for 3 buttons for example.

**Comment by adviseore** [comment]
> Hi,
> 
> Sega Genesis/Megadrive -> Input
> 
> Global | Port 1 | Port 2
> 
> Input device: none gamepad gamepad2 gamepad6 megamouse
> 
> Select the port, then under "Input device", you can choose which type of gamepad you want to configure. 2/3/6 buttons or megamouse. You most likely have gamepad2 set up for Port1, change it to gamepad for 3 buttons for example.

Excellent! I cant believe I didn't check that. Thank you, problem solved.
