### ISSUE TITLE
NHL 98 will not give up showing this error

### ISSUE THREAD

**Issue by jlnhlfan** [AmatCoder/mednaffe#173]
![image](https://github.com/AmatCoder/mednaffe/assets/31529087/8946e46b-05e7-4317-9570-70f0ea9aaf9a)

I'm trying to play NHL 98 with this frontend, but no matter what expansion cart I use, this error will always show up. Is there such a thing as a way to ensure this error doesn'r show up, or is the game screwed?

**Comment by AmatCoder** [comment]
This is not a frontend but emulator issue (if it is).
