### ISSUE TITLE
Mednaffee (Flatpak) not seeing all drives

### ISSUE THREAD

**Issue by ZeddieXX** [AmatCoder/mednaffe#174]
I have another internal SSD drive I have all my ROMs but Mednaffe isn't showing it in the file picker.

I'm on Fedora 39 and Mednaffee was downloaded from the Software store app.

I think it may be a permissions issue, but unsure how to fix it (not a Linux/Flatpak expert).

**Comment by yioannides** [comment]
Download Flatseal from Flathub, go to Mednaffe > Filesystem and add the `/mnt` path in Other files.

Since flatpaks are running in a sandbox, they cannot see anything outside the Home folder by default, unless you give them access to other folders.
