### ISSUE TITLE
how do i use gbc palettes for gb games?

### ISSUE THREAD

**Issue by shyguy85** [AmatCoder/mednaffe#178]
how do i use gbc palettes for gb games? ive tried launching in gbc mode but the colors are still grey.

**Comment by AmatCoder** [comment]
You should ask that in [Mednafen forum](https://forum.fobby.net/)

**Comment by ghost** [comment]
I've put together a set of palettes with instructions a while ago, here you are: https://ln5.sync.com/dl/4d2597250/wzx68js7-s9rg5k74-equ72fpe-39bcawm7

:)
