### ISSUE TITLE
[Request] Folder structure

### ISSUE THREAD

**Issue by Papermanzero** [AmatCoder/mednaffe#18]
Currently mednaffe and mednafen must be in the same folder to work.
Furthermore mednafen always creates a lot of sub folders which are not necessarily relevant (e.g. for savestates, bios, roms etc.).So it would be convenient if mednafen can be placed in different folders like a "mednafen core folder". Also a system or data folder for mednaffe itself would be great (for the data files).The benefit would be an improvement of the structure and overview of mednaffe and the root folder.

**Comment by AmatCoder** [comment]
Next version will not need to be in the same folder than mednafen.
 If mednaffe does not find mednafen executable it ask you for it. This means that mednafen could be placed into whichever folder.

I'm not sure what you mean about 'data files' from mednaffe. Executable is the only thing needed to work.

**Comment by Papermanzero** [comment]
Sorry my fault.
I thought you have further data or library files (e.g. dll, cfg...) which could be packed into a folder. 
But these files belong to mednafen.
Actually you only have one executable and a ini file, which will be created after the first boot.
So the implementation you did is great and fully sufficient to create a folder structure. :)
Thank you so much.

**Comment by AmatCoder** [comment]
In e8ee7f8 commit I have implemented the ability to select a mednafen executable in another folder if it is not found.
