### ISSUE TITLE
[BUG] XInput maps always Axis - deadzones required

### ISSUE THREAD

**Issue by tapcio** [AmatCoder/mednaffe#19]
Microsoft gamepads are crappy so they need deadzone for axis and triggers, Xinput.h defines them:

    #define XINPUT_GAMEPAD_LEFT_THUMB_DEADZONE  7849
    #define XINPUT_GAMEPAD_RIGHT_THUMB_DEADZONE 8689
    #define XINPUT_GAMEPAD_TRIGGER_THRESHOLD    30

I have mapping problem because of this ie. axis movement is reported as 'key pressed' in PSX Input mapping.

**Comment by AmatCoder** [comment]
Analog inputs are not supported yet, so they acts like digital buttons.

**Comment by tapcio** [comment]
I think you misunderstand me. I explain using example:
I want to map button 'A' to PSX button 'X'. When I press 'A' on gamepad, then GUI sets 'Axis 1 Down' or similar instead, so I cannot map digital buttons because axes are always detected as pressed (because then not center ideally).
Also I think GUI is saving improper device string, Mednafen saved setting like:
````
;psx, Virtual Port 1, DualShock: Analog(mode toggle)
psx.input.port1.dualshock.analog joystick 0000000000010000 0000000a

;psx, Virtual Port 1, DualShock: ○ (right)
psx.input.port1.dualshock.circle joystick 0000000000010000 0000000d

;psx, Virtual Port 1, DualShock: x (lower)
psx.input.port1.dualshock.cross joystick 0000000000010000 0000000c
````

**Comment by AmatCoder** [comment]
I misunderstand you, sorry. Now I see what you mean.
This happens also with DirectInput devices if analog controls are not center perfectly.
I will add deadzones to avoid this. Thanks for reporting.

---

Regarding to device string, mednafen does not use dwUserIndex to identify gamepads but it use an internal ID. Basically it is like:
`id = (XINPUT_DEVTYPE_GAMEPAD << 24) | (XINPUT_DEVSUBTYPE_GAMEPAD << 16);	`
So '0000000000010000' seems an correct id from a Xinput device.
(Probably I am misunderstand you again... ;) )

**Comment by AmatCoder** [comment]
Deadzones for axis added in ab1bbc6 commit.

You can test it downloading this: 
https://sites.google.com/site/amatcoder/mednaffe_8b_test.zip?attredirects=0&d=1

**Comment by tapcio** [comment]
LGTM :+1:

**Comment by AmatCoder** [comment]
Great! Thanks for testing.

**Comment by mistertoze** [comment]
Hello, I'm also having issues with the deadzones in my controller.

Is there any way I can increase their value?
Or would it be possible for you to add deadzone sliders to the Input options?

Thank you.
