### ISSUE TITLE
[Request] Add psx.input.port x.dualshock.axis_scale setting in gui

### ISSUE THREAD

**Issue by BParks21** [AmatCoder/mednaffe#20]
This is hard for average users to configure without some kind of gui option. It's needed for people using 360 or Xbox one controllers.

**Comment by AmatCoder** [comment]
All input options will be included in the next version.

**Comment by WizLizard** [comment]
@AmatCoder Cool I'm really glad to here that. I love this frontend it's so simple. Can't wait thanks!

**Comment by WizLizard** [comment]
@AmatCoder I noticed you released 0.8.1. Is this feature not coming until 0.9? If so will we see that release soon?

**Comment by WizLizard** [comment]
@AmatCoder What is the status of this feature?

**Comment by AmatCoder** [comment]
This is still unimplemented.
I do not have much time to implement new features. I will try it but I can't promise anything, sorry.

**Comment by vpontin** [comment]
Any news about this?

**Comment by ThatAnnoyedGuy** [comment]
Is this feature still being implemented?

Thank you

**Comment by AmatCoder** [comment]
Yes, it has been implemented.
If you use Linux you can compile master branch to test it.

**Comment by AmatCoder** [comment]
Added in 0.9.0 version.
