### ISSUE TITLE
Window Position is changing

### ISSUE THREAD

**Issue by Papermanzero** [AmatCoder/mednaffe#22]
The window position in mednaffe is changing after the user closed and opened mednaffe again.
Mean you can shift the windows of mednaffe to the right screen corner, but after a restart it is in the middle of the screen. The latest mednaffe build with Windows 7 x64 is used.

**Comment by AmatCoder** [comment]
Sorry for my late reply.

I've been able to confirm that. Not sure if bug or normal behavior on Windows, though.
Anyway, I will create an option to remember window position.

Thanks for reporting.

**Comment by Catarax** [comment]
Can be closed?

**Comment by AmatCoder** [comment]
No, this is a different issue and it is not fixed yet.
Mednaffe starts always on the center of the screen. It should remember the last position on the screen 
when restart.

**Comment by AmatCoder** [comment]
Added in 0.9.0 version.
