### ISSUE TITLE
Request: For Folder Directory Structure Changed...

### ISSUE THREAD

**Issue by Geyup** [AmatCoder/mednaffe#23]
Hi,

First let me say thank you very much for this awesome program!

I think it would be nice if mednafee had a different gui folder structure.

Right now you have to add folders for every directory you have games in. I personally like to keep my games in their own folders for what I think is better organization, at least for me hehe...

Here's how my game folders look;

/home/foo/Game/PSX
/home/foo/Game/PSX/Chrono Cross
/home/foo/Game/PSX/Fear Effect
/home/foo/Game/PSX/Final Fantasy IX
/home/foo/Game/PSX/Final Fantasy VII

As you can see each game has it's own directory under `/home/foo/Game/PSX` but this is just for PSX games.  Then for PS2 games, or Sega games I break those up into further directories...

/home/foo/Game/PS2
/home/foo/Game/Sega

I would really love it if I didn't have to add a folder for every directory I had a game in. It would really be nice if mednaffe could be made, that all you needed to do was just add the `Top Parent` /path which for me is just, `/home/foo/game` and then have all the directories show up, probably more like a File Manager does.

I personally think something like this makes it easier for the end-user to keep organized.

Thank you very much for your consideration! :)

**Comment by AmatCoder** [comment]
Sorry for late reply.

Have you tried 'Recursive' option? I think that it's what you're looking for.

You can to add '/home/foo/Game/PSX' folder and then click on 
View->List->Scan Mode->Recursive (or press Shift+R).
All files under '/home/foo/Game/PSX' and its subdirectories will be shown.

Regards.

**Comment by tapcio** [comment]
Also will be nice for m3u to filter cue files included in m3u.

**Comment by AmatCoder** [comment]
@tapcio, Do you mean an option to show only m3u files?

**Comment by tapcio** [comment]
Problem is when you add cue files to m3u then you have cue files and m3u on list but you only want m3u for multidisk games: http://i.imgur.com/DxyiB4g.png

**Comment by AmatCoder** [comment]
I see. An option to hide cue files already included in m3u files.

**Comment by Geyup** [comment]
@AmatCoder no worries on the reply. :)

Well ```Recursive``` helps, but if you have a lot of games, then you're going to dig around through the list of everything.

I'd still rather like to see a layout that shows the directories the games are in as I mentioned, then go into that directory, like a File Manager.

**Comment by Geyup** [comment]
Hi,

Any chance to get a reply?

thanks

**Comment by AmatCoder** [comment]
This is not going to be implemented, sorry.

Summarizing: I think that user must be who organizes roms and folders in the best way possible, not mednaffe.

**Comment by Geyup** [comment]
HOLY CRAP 5 months later a reply LOL...

OK...
