### ISSUE TITLE
BUG supposed missing config

### ISSUE THREAD

**Issue by DanHolli123** [AmatCoder/mednaffe#24]
I had mednafen installed an the config created but when i start mednaffe it says, "Error: No mednafen configuration file found." I checked in ".mednafen" an the config is still there

**Comment by AmatCoder** [comment]
Check if "echo $HOME" gives you the correct home directory.
Also check if configuration file is correctly named (_mednafen-09x.cfg_) and you have read permissions for the file (i.e. you can open it with a text editor).

**Comment by DanHolli123** [comment]
the "echo $HOME" gave...
/home/'my user name' will try moving config in case it doesn't work

**Comment by DanHolli123** [comment]
still didn't work

**Comment by arcooke** [comment]
Same issue here

![](http://i.imgur.com/P5aeEW0.png)

**Comment by arcooke** [comment]
I poked through the source for a bit and figured out what's going on.

It is because mednaffe is searching for mednafen-09x.cfg in ~/.mednafen/ .. which is part of Mednafen 0.9.x

Ubuntu's repositories have not updated mednafen on Trusty since 2013 and has 0.8.D.3-6 https://launchpad.net/ubuntu/+source/mednafen

So anyone running 14.04 or Mint 17.x etc will get this error.

**Comment by DanHolli123** [comment]
OK and thanks for explaining the reason

**Comment by alebersol** [comment]
Same error.

Mednafen version is 1.21.3
Starting Mednafen 
 Build information:
   Compiled with gcc 7.3.0
   Compiled against zlib 1.2.10, running with zlib 1.2.10(flags=0x000000a9)
   Compiled against SDL 2.0.8(hg-11914:f1084c419f33), running with SDL 2.0.8(hg-11914:f1084c419f33)
   Running with libsndfile-1.0.27
 Base directory: /home/alessandro/.mednafen
 Emulation modules: nes snes gb gba pce lynx md pcfx ngp psx ss ssfplay vb wswan sms gg snes_faust pce_fast demo cdplay
 Opening lockfile...
 Loading settings from "/home/alessandro/.mednafen/mednafen.cfg"...
  Loaded 7396 valid settings and 0 unknown settings.
No command-line arguments specified.

Usage: mednafen [OPTION]... [FILE]
	Please refer to the documentation for option parameters and usage.

Mednaffe message Error: No mednafen configuration file found.
Mednaffe is 0.8.8
