### ISSUE TITLE
Request: write to config file instead of keeping list of command line args

### ISSUE THREAD

**Issue by TiZ-EX1** [AmatCoder/mednaffe#26]
Hi there. I already have a sort of front-end for starting up my games, so I don't need a GUI in that sense. However, mednafen's config file is giant and a huge pain to deal with so I'd definitely like a GUI for configuring it. When I compiled mednaffe, I was very confused to see that it seemed none of my settings were being saved. After all, I wasn't starting any of my games through mednaffe; I just wanted to configure mednafen. It made sense though when I looked at mednaffe's own config file and saw that it was saving config changes by keeping a list of command line args.

I'd like the ability to modify the config file through the GUI, at least as an option if not as default behavior. Thanks for your work on this program.

**Comment by AmatCoder** [comment]
You just have to launch one game through mednaffe and emulator settings will be saved.
Then you will be able to start games with your front-end with new settings.
Thereby you can use mednaffe for just to configure mednafen emulator.
