### ISSUE TITLE
[Request] Possibility to add you own command-line options

### ISSUE THREAD

**Issue by Nucleoprotein** [AmatCoder/mednaffe#27]
Hello,

I have build custom Mednafen with psx widescreen option so I want to have possibility to use it from mednaffe gui, and adding universal way to add commandline options will be very good in general.

**Comment by AmatCoder** [comment]
I am agree, request accepted.
Thanks for suggestion.

**Comment by AmatCoder** [comment]
Added in 0.9.0 version.
