### ISSUE TITLE
Request: Filetype filter system-specific

### ISSUE THREAD

**Issue by rdanbrook** [AmatCoder/mednaffe#29]
I think it makes sense to move the "All files/Only zips/Only cue/toc/ccd/m3u" to be a system-specific option. Disc image systems vs ROM systems are usually going to be distributed differently. Actually a more advanced filter option for certain uncompressed rom filename extensions might make sense too (such as .nes and .md).

**Comment by AmatCoder** [comment]
Yes, I know that filter options are a bit inconvenient. Let's me think about this.

**Comment by AmatCoder** [comment]
Implemented on 18905b6 commit.
Now you can choose that filetypes are shown on a per-folder basis.
