### ISSUE TITLE
[Request] Controller Setup in GUI

### ISSUE THREAD

**Issue by GoogleCodeExporter** [AmatCoder/mednaffe#3]
```
Setting up a controller scheme inside Mednafen is simple enough, but it could 
be a lot easier and better to do it right in Mednaffe. There could be a 
universal control setup for all the emulators and/or a way to input them on an 
individual basis to make it override the universal scheme. Having a diagram of 
a controller visible whilst inputting the buttons is always helpful as well. 
Also being able to assign rewind, save state, and load state to controller 
buttons would be nice, too.
 
What version of the product are you using? On what operating system?
mednaffe-0.5 with mednafen-0.9.32-wip-win32 in Windows 7 64bit

Please provide any additional information below.
I know this request is probably not easy to do at all, but thank you for any 
consideration on this topic.

```

Original issue reported on code.google.com by `StarrySk...@gmail.com` on 13 Nov 2013 at 7:49

**Comment by tony971** [comment]
Any progress on this?

**Comment by AmatCoder** [comment]
Actual (Apr 19) state is:

Linux
* Basic controller configuration for keyboard and gamepads/joysticks: Developed, working and uploaded to github.

Windows:
* Basic controller configuration for keyboard: Developed, working and uploaded to github.
* Basic controller configuration for DirectInput gamepads/joysticks: Developed and working. To be tested and uploaded.
*  Basic controller configuration for Xinput gamepads/joysticks: To be developed.


A screenshot from Linux:

![2015-04-19--1429475195_1043x762_scrot](https://cloud.githubusercontent.com/assets/3890995/7221274/8615f3aa-e6e4-11e4-879a-f5974910e167.png)

**Comment by SwinglesMan** [comment]
Got emucr build. Doesn't seem to be working. I double click and nothing happens. Using windows build. Mednafen x86 build. Tried x32 build as well.
