### ISSUE TITLE
Some settings are not saving on GalliumOS (systems list, rom folders)

### ISSUE THREAD

**Issue by arcooke** [AmatCoder/mednaffe#31]
I have Mednaffe on my main desktop (Mint 17.3, Ubuntu 14.04 base), and my Chromebook (GalliumOS, Ubuntu 16.04 base)

On my desktop, everything saves fine. 

On Gallium, the rom folders I add on the main dialog do not save after I exit and re-run Mednaffe.  The list is empty when it starts back up.  It also does not save my system selections.  I disabled all but 4 systems, exited, re-opened Mednaffe, and all 15 systems were back.

It DOES save per-system settings just fine.  Like I set the supereagle video filter on SNES/NES, and those settings saved.

I don't expect anyone to test on Gallium, but I am assuming it would be the same result on Ubuntu 16.04.

I'm not sure if it's a file permission issue or what.  Where are these configs being saved to?

**Comment by AmatCoder** [comment]
Most probably this is the same issue than #34 so it is fixed with [0.8.3](https://github.com/AmatCoder/mednaffe/releases/tag/v0.8.3) release. Reopen this issue if not.
