### ISSUE TITLE
Saturn GUI for mednafen 0.9.39.x support

### ISSUE THREAD

**Issue by sljunkie** [AmatCoder/mednaffe#36]
[mednafen 0.9.39.x](http://forum.fobby.net/index.php?t=rview&goto=4409&th=1326#msg_4409) is out for a while, and its most notable feature is **Saturn support**, and from what I've heard this emulation core is pretty good.

Mednaffe ought to implement a Sega Saturn System GUI in the near future.

**Comment by AmatCoder** [comment]
It was implemented a few weeks ago on e2d8d03 commit.
If you use Windows you can try this [test version](http://forum.fobby.net/index.php?t=getfile&id=893&).

**Comment by AmatCoder** [comment]
Fixed with [0.8.3](https://github.com/AmatCoder/mednaffe/releases/tag/v0.8.3) release.
