### ISSUE TITLE
Provide contact information on README.md

### ISSUE THREAD

**Issue by tukkek** [AmatCoder/mednaffe#39]
Hello, this is more of a personal message for @AmatCoder. I couldn't find a way to get in touch with you either through your personal Google website, GitHub information and your reddit account also seems to be inactive. You should consider adding an e-mail address somewhere for people who want to get in touch with you regarding mednaffe with questions, bug reports, improvement ideas, etc. Some people don't have a GitHub account and some topics (like people who want to ask you questions that aren't in your FAQ) are not suitable for a bug tracker either.

**Comment by AmatCoder** [comment]
Bug reports, improvement ideas and questions that could fit into the FAQ should been reported here.

Other questions could be asked in this [thread](http://forum.fobby.net/index.php?t=msg&th=941&start=0&) on Mednafen Forum.

That kind of things should be public discussions. If not people would ask me the same questions a lot of times. However questions posted here are searchable on the internet.

Summarizing: An e-mail address is a kind of private support that is not suitable.

**Comment by tukkek** [comment]
It's a shame that people need to create an account on GB or the forum to
talk to you, not to mention find that thread first. If it were me, I'd
create an e-mail account and just ignore questions that are in the FAQ,
possibly even set up an auto-response with that information. Anyway it's
your project and your choice, best of luck with it!
