### ISSUE TITLE
Dots in filenames

### ISSUE THREAD

**Issue by goberghen** [AmatCoder/mednaffe#42]
If there are dots in snaps/roms filenames (i.e. “Super Mario Bros. 3 (U) (PRG1) [!].nes”), snapshots in sidebar are failed to appear. Same with “Hide file extentions” option in “Folder setup” (i.e. all Super Mario Bros. 1/2/3 roms names are truncated just to Super Mario Bros).

**Comment by AmatCoder** [comment]
Fixed on a5800b4 commit.
Thanks for reporting.

**Comment by goberghen** [comment]
Thank you.
