### ISSUE TITLE
32-bit installs shouldn't show Sega Saturn by default.

### ISSUE THREAD

**Issue by doyousketch2** [AmatCoder/mednaffe#46]
Sega Saturn can only run on 64-bit systems, 
so it should either be unchecked to begin with, 
or that option should be completely greyed-out / hidden on 32-bit installs.

**Comment by AmatCoder** [comment]
I know but I believed that mednafen emulator will get Saturn support on 32-bit in the near future.
Now I am not sure according to this: http://forum.fobby.net/index.php?t=msg&th=1382&start=0&
I will ask on IRC.

**Comment by AmatCoder** [comment]
With 0.9.0 version, Saturn options are greyed-out on 32-bit.
