### ISSUE TITLE
Where is autofire, if any?

### ISSUE THREAD

**Issue by Wesley-Chan** [AmatCoder/mednaffe#47]
I was playing some NES game last night. It would be great if we have this.

**Comment by AmatCoder** [comment]
Mednafen emulator has autofire options (like 'nes.input.port1.gamepad.rapid_a').
I will implement them into mednaffe front-end for next release.

**Comment by retro-wertz** [comment]
please include config for turbo/rapid buttons.

thanks.

**Comment by AmatCoder** [comment]
It is already implemented on master branch.

**Comment by AmatCoder** [comment]
Added in 0.9.0 version.

**Comment by Eggo-dotcom** [comment]
this is missing on tg-16/pce where it is essential
