### ISSUE TITLE
Support for Mednafen 0.9.41

### ISSUE THREAD

**Issue by Xray662** [AmatCoder/mednaffe#48]
Hello, please update mednaffe to actual mednafen version when it's will be possible ;)

**Comment by AmatCoder** [comment]
Work in progress on this [branch](https://github.com/AmatCoder/mednaffe/commits/0.8.x).

**Comment by AmatCoder** [comment]
Version 0.8.4 has been [released](https://github.com/AmatCoder/mednaffe/releases/latest) fixing this issue.
