### ISSUE TITLE
Not complete full Window position saved

### ISSUE THREAD

**Issue by Catarax** [AmatCoder/mednaffe#49]
The window position is not exactly saved when adjusted to the maximum (windows 10 anniversary).

**Before closing:**
![screenshot_1](https://cloud.githubusercontent.com/assets/3964507/22259636/64776b78-e266-11e6-8974-7ef7db037076.png)

**Re-opened at startup:**
![screenshot_2](https://cloud.githubusercontent.com/assets/3964507/22259644/657353ac-e266-11e6-9626-702ba478771c.png)

**Comment by Catarax** [comment]
Seems to be fixed on latest version.

**Comment by Catarax** [comment]
Don't know, got it to work, then can't redo it.

**Comment by Catarax** [comment]
So ok, to fix this issue, I have to create a shortcut of Mednaffe to get my full window.

**Comment by AmatCoder** [comment]
Window in screenshot 1 is in maximized state.
Mednaffe don't save states of the window, only size.
But I'll try to implement it.

**Comment by AmatCoder** [comment]
Fixed in 0.9.0 version.
