### ISSUE TITLE
French accents not supported in game list

### ISSUE THREAD

**Issue by Catarax** [AmatCoder/mednaffe#51]
Game like : "L'héritage de Goku" will not display the "é"
![screenshot_1](https://cloud.githubusercontent.com/assets/3964507/22268943/af29d822-e289-11e6-8793-af8963fd3c43.png)

**Comment by AmatCoder** [comment]
Yes, Windows version does not display Unicode characters because:

- Mednafen emulator does not need them.
- Scaning files is slower (It needs convert every filename).

But it can be added as option.

**Comment by Catarax** [comment]
So could it be possible to have the character without the accent if it doesn"t impact perf? Thanks

**Comment by AmatCoder** [comment]
No, but perfomance is only x3 slower. You will not notice unless you have more than a few thousand files in the list.

**Comment by AmatCoder** [comment]
Fixed in 0.9.0 version.
