### ISSUE TITLE
Box art

### ISSUE THREAD

**Issue by polsvoice** [AmatCoder/mednaffe#53]
I would like an option to display box art instead of, or in addition to, snapshots.

**Comment by AmatCoder** [comment]
What do you mean? You can already display box art instead of snapshots as long as they are png files.

**Comment by polsvoice** [comment]
What dimensions do they need to be? All of the ones I've tried have been too big to display properly, and they mess up the sizing of the window. I think it would be cool if it would automatically resize them for me and allow me to select the file instead of having to rename it.

It's interesting to note that the files don't actually have to be PNGs in order to display; they only need to have the .png extension. For example, if you take Abadox (U).jpg and rename it to Abadox (U).png, it will work.

**Comment by AmatCoder** [comment]
Ah, I see now . Large images need scaling to fit into window. This is a bug.

> It's interesting to note that the files don't actually have to be PNGs in order to display; they only need to have the .png extension. For example, if you take Abadox (U).jpg and rename it to Abadox (U).png, it will work.

Only on Linux (and if **GdkPixbuf** is compiled with jpeg support) because file format is detected automatically despite of filename.

On Windows, Mednaffe is compiled without jpeg support so this does not work.

**Comment by AmatCoder** [comment]
Fixed on 7fbe245 commit.
Some minor bugs/warnings remains.
