### ISSUE TITLE
ability to manually filter files extensions in game list

### ISSUE THREAD

**Issue by arthur071169** [AmatCoder/mednaffe#54]
Firstly, this is a great (ans simple) program.  a lot less faff than Launchbox etc. (although artwork would be nice - that is not my question here though).

I have a (very) large collection of trurips that in a great many cases have a folder/game with cue/bin only,  and another folder/game with cue/ccd/sub/bin

Is it possible to exclude the ccd files from the gamelist as both the ccd and cue appear for titles that have these. 
perhaps instead of a hard codded option to 'only show cue/toc/ccd/m3u'  we can tick what to show per system?

thanks,
Arthur.

**Comment by AmatCoder** [comment]
This is already implemented and will be available in the next version (albeit not per-system but per-folder).

One screenshot:
![mednaffe_0 9 0beta](https://cloud.githubusercontent.com/assets/3890995/23666966/57f5d556-0354-11e7-8453-184746393477.png)

**Comment by arthur071169** [comment]
Fantastic!
Starting to look a bit like (the excellent) gamebase front end.
I await this version being available on Github.

Kind regards,
Arthur.

**Comment by arthur071169** [comment]
any update on a potential release date for the above version?

**Comment by AmatCoder** [comment]
No, sorry. I am very busy lately.

**Comment by CaioVdmm** [comment]
Amat only the master branch of mednaffe has this feature, the mednaffe 8.7 and 8.8 does not have this.
these two versions have only one option in the menu bar to filter for some predetermined extensions

**Comment by anewuser** [comment]
@CaioVdmm I'm pretty sure that the developer of the project is aware of what features each version has.  Please don't leave comments like that on open source repositories. New features are always going to be added only when the developers have enough time to finish and test them.

**Comment by AmatCoder** [comment]
Added in 0.9.0 version.
