### ISSUE TITLE
Very simple mame support

### ISSUE THREAD

**Issue by mikweb** [AmatCoder/mednaffe#55]
Hi guys,

My idea is to use mednaffe for game listing (add folder capability), and just run 'mame romname' command on game start (only mame executable path have to be set in configuration).

All Mame GUIs merge games and bios. I want just to list my roms collection located in a folder. 

Hope you can help me,

**Comment by AmatCoder** [comment]
This would be a nice side project but it will not be a goal for Mednaffe.
