### ISSUE TITLE
Option to enable SNES mouse

### ISSUE THREAD

**Issue by polsvoice** [AmatCoder/mednaffe#56]
The Super NES Mouse supports [a few dozen games.](https://en.wikipedia.org/wiki/Super_NES_Mouse) You can enable emulation of the SNES Mouse by changing snes.input.port1 in the config file to "mouse". I would like to see an option in mednaffe to switch from the gamepad to the mouse.

**Comment by AmatCoder** [comment]
All input options are planned to be included but I do not have time lately to implement them.

**Comment by AmatCoder** [comment]
Added in 0.9.0 version.
