### ISSUE TITLE
Use 6-button gamepads for Sega MD

### ISSUE THREAD

**Issue by di72nn** [AmatCoder/mednaffe#57]
Configure `gamepad6` instead of `gamepad` for Sega Mega Drive/Genesis.

You need to replace `gamepad` with `gamepad6` in `-md.input.port1.gamepad6.*`, set `-md.input.port1.gamepad6.{x,y,z}`, and add `-md.input.port1 gamepad6`. The same goes for `port2`.

~~AFAIK, 6-button gamepads have no disadvantages in comparison to 3-button ones.~~ I've just realized some people might want to use the default `gamepad` option (e. g.: if their physical gamepad doesn't have enough buttons; some games may detect that a 3-button gamepad is connected and provide simplified controls). So `gamepad6` option should be optional.

**Comment by AmatCoder** [comment]
All input options are planned to be included but I do not have time lately to implement them.

**Comment by AmatCoder** [comment]
Added in 0.9.0 version.
