### ISSUE TITLE
Mednaffe was working fine then began crashing and wont stop

### ISSUE THREAD

**Issue by RustyMcClintock** [AmatCoder/mednaffe#58]
I'm using Mednaffe on lubuntu 17.04 on some dated hardware. When I installed it it worked like Icharm on the Visualboy at least. At one point I changed the display mode to verticalinterlaced and it crashed when Itried to start. Ever since then it crashes every time Itry and launch regardless of the rom I use. Here is the emulater log:

Executing mednafen with command line: 
"/usr/games/mednafen -psx.dbg_level 0 -psx.region_default jp -vb.anaglyph.rcolor 0xA40000 -video.fs 0 -nes.fnscan 0 -vb.anaglyph.lcolor 0xCC0000 -vb.disable_parallax 1 -ss.region_autodetect 0 -vb.stretch aspect_mult2 -vb.cpu_emulation fast -vb.anaglyph.preset disabled -psx.region_autodetect 0 -lynx.stretch aspect_mult2 -cheats 1 -ss.region_default jp -vb.3dmode anaglyph -debugger.autostepmode 1 -vb.liprescale 3 -vb.input.builtin.gamepad.up-l joystick 630f0eab74165481 0000c006 /home/rusty/Downloads/Red Alarm (USA).zip "
----
Starting Mednafen 0.9.41
 Build information:
   Compiled with gcc 6.3.0 20170121
   Compiled against zlib 1.2.8, running with zlib 1.2.11(flags=0x00000055)
   Compiled against SDL 1.2.15, running with SDL 1.2.15
   Running with libsndfile-1.0.27
 Base directory: /home/rusty/.mednafen
 Emulation modules: nes snes gb gba pce lynx md pcfx ngp psx ssfplay vb wswan sms gg snes_faust pce_fast demo cdplay
 Loading settings from "/home/rusty/.mednafen/mednafen-09x.cfg"...
  Loaded 3191 valid settings and 0 unknown settings.
Unrecognized argument: -ss.region_autodetect
----
End of execution caught.

And one from the front end:

Executing mednafen with command line: 
"/usr/games/mednafen -psx.dbg_level 0 -psx.region_default jp -vb.anaglyph.rcolor 0xA40000 -video.fs 0 -nes.fnscan 0 -vb.anaglyph.lcolor 0xCC0000 -vb.disable_parallax 1 -ss.region_autodetect 1 -vb.stretch aspect -vb.cpu_emulation fast -vb.anaglyph.preset disabled -psx.region_autodetect 0 -lynx.stretch aspect_mult2 -cheats 1 -ss.region_default jp -vb.3dmode anaglyph -vb.liprescale 3 -vb.input.builtin.gamepad.up-l joystick 630f0eab74165481 0000c006 /home/rusty/Downloads/Sonic the Hedgehog 2 (World).zip "
***ERROR***: Unrecognized argument: -ss.region_autodetect
End of execution caught.

I have tried uninstalling via packagemanager and via terminal and manuallydeleting the cfg file. I've tried sudo apt-get autoremove and everything I know. I'm relatively new to linux so this may be ovcious to someone else but I'm still learning this OS. I thinkmaybe its trying to use allthe emulaters at once? I'm not too sure. Maybe you could help me figure out whats gone wrong?

**Comment by AmatCoder** [comment]
Are you using a x86 version of Lubuntu?
Note that Saturn emulation is only compiled for builds for some 64-bit architecture like x86_64 ([source](https://mednafen.github.io/documentation/ss.html)).

x86 builds of mednafen emulator do not contain any settings from Saturn, so if you change any of them into Mednaffe front-end you get an error like that (Unrecognized argument).

You can delete _"/home/$USER/.config/mednaffe.conf"_  file as workaround.

**Comment by RustyMcClintock** [comment]
That fixed it immediately, I assume this folder you've shown me is a usual place for such configuration files so i can try and remember that in the future. Thank you so much for your help, I had been real bummed when I couldn't get it to work because I really liked playing Wario Land again all these years later. I'll hide the Saturn settings this time around. Thanks for doing such a good job on this program.

**Comment by AmatCoder** [comment]
With 0.9.0 version, this issue is no longer possible.
