### ISSUE TITLE
Multitap support for Playstation

### ISSUE THREAD

**Issue by DLPB2** [AmatCoder/mednaffe#59]
I can't get this working, so I assume it isn't implemented yet?

**Comment by Catarax** [comment]
Enable it in-game with the shortcut keys.

**Comment by DLPB2** [comment]
That still doesn't change the fact that Mednaffe does not support multiple joypads in the GUI?

**Comment by Catarax** [comment]
I don't speak about the config file but about using a shortcut key while playing as a temporar solution since "you never got it working". Hope you liked my help.

**Comment by AmatCoder** [comment]
All input options are planned to be included, but Mednaffe is being rewritten so it can take a lot of time.

**Comment by DLPB2** [comment]
Thanks :)

**Comment by Mte90** [comment]
any updates?

**Comment by AmatCoder** [comment]
Added in 0.9.0 version.
