### ISSUE TITLE
Error to put the GE bios of Pcengine

### ISSUE THREAD

**Issue by Pcegames** [AmatCoder/mednaffe#62]
For some reason the front end closes when I try to put the bios in the field.
This has already happened some time with other old versions of Mednafe.
My English is quite rusty but I am practicing.

http://prntscr.com/g30136

**Comment by AmatCoder** [comment]
Yes, object was not defined and therefore it was not passed by signal. 
Fixed on 25d630c commit.

Thanks for reporting.
