### ISSUE TITLE
Games don't launch

### ISSUE THREAD

**Issue by HoomanIsHere** [AmatCoder/mednaffe#66]
Everytime I try to launch a Virtual Boy game (.vb), it doesn't work. I click everything, but the game won't launch. What to do?

**Comment by AmatCoder** [comment]
Take a look at the text contained into tabs Logs->Emulator.

If you don't get any hint then you can copy and paste it here to see what happens.

**Comment by HoomanIsHere** [comment]
Executing mednafen with command line: 
"C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\mednafen.exe" -vb.input.builtin.gamepad.right-l "keyboard 100" -vb.input.builtin.gamepad.b "keyboard 98" -vb.input.builtin.gamepad.a "keyboard 118" -vb.input.builtin.gamepad.left-l "keyboard 97" -vb.input.builtin.gamepad.lt "keyboard 113" -vb.input.builtin.gamepad.start "keyboard 13" -vb.input.builtin.gamepad.down-r "keyboard 107" -vb.input.builtin.gamepad.select "keyboard 92" -vb.input.builtin.gamepad.down-l "keyboard 115" -vb.input.builtin.gamepad.up-r "keyboard 105" -vb.input.builtin.gamepad.rt "keyboard 101" -vb.input.builtin.gamepad.right-r "keyboard 108" -vb.input.builtin.gamepad.left-r "keyboard 106" -vb.input.builtin.gamepad.up-l "keyboard 119" -psx.dbg_level "0" "C:\Users\Cythes\Desktop\Games and apps\Emulators\Virtual Boy Wario Land (Japan, USA).vb"

**Comment by AmatCoder** [comment]
Hmm, that's weird.

Please, can you paste the text from **stdout.txt** file?

**Comment by HoomanIsHere** [comment]
Запускается Mednafen 0.9.48
 Build information:
   Compiled with gcc 4.9.4
   Running with MinGW-W64 Runtime 5.0 (alpha - rev. 0) 0000-00-00
   Compiled against zlib 1.2.8, running with zlib 1.2.8(flags=0x00000065)
   Compiled against libiconv 15.1, running with libiconv 15.1
   Compiled against SDL 1.2.15, running with SDL 1.2.15
   Running with libsndfile-1.0.28
 Base directory: C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen
 Emulation modules: nes snes gb gba pce lynx md pcfx ngp psx ss ssfplay vb wswan sms gg snes_faust pce_fast demo cdplay
 Loading settings from "C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\mednafen-09x.cfg"...
  Loaded 6110 valid settings and 0 unknown settings.
 Initializing joysticks...
  Joystick 0 - XInput Unknown Controller - Unique ID: 0000000000010000
 Loading C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\Virtual Boy Wario Land (Japan, USA).vb...
  Применение файла IPS «C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\Virtual Boy Wario Land (Japan, USA).vb.ips»...
   Failed: Error opening file "C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\Virtual Boy Wario Land (Japan, USA).vb.ips": No such file or directory
  Using module: vb(Virtual Boy)
   Loading override settings from "C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\vb.cfg"...
    Failed: Error opening file "C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\vb.cfg": No such file or directory
   Loading override settings from "C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\pgconfig\Virtual Boy Wario Land (Japan, USA).vb.cfg"...
    Failed: Error opening file "C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\pgconfig\Virtual Boy Wario Land (Japan, USA).vb.cfg": No such file or directory

**Comment by HoomanIsHere** [comment]
Excuse the Russian language.

**Comment by AmatCoder** [comment]
Hmm, it seems that some lines are missing.
For example my stdout.txt is:
```
Starting Mednafen 0.9.48
 Build information:
   Compiled with gcc 4.9.4
   Running with MinGW-W64 Runtime 5.0 (alpha - rev. 0) 0000-00-00
   Compiled against zlib 1.2.8, running with zlib 1.2.8(flags=0x00000065)
   Compiled against libiconv 15.1, running with libiconv 15.1
   Compiled against SDL 1.2.15, running with SDL 1.2.15
   Running with libsndfile-1.0.28
 Base directory: C:\test with spaces\mednafen-0.9.48-win64
 Emulation modules: nes snes gb gba pce lynx md pcfx ngp psx ss ssfplay vb wswan sms gg snes_faust pce_fast demo cdplay
 Loading settings from "C:\test with spaces\mednafen-0.9.48-win64\mednafen-09x.cfg"...
  Loaded 6110 valid settings and 0 unknown settings.
 Initializing joysticks...
 Loading C:\test with spaces\Virtual Boy Wario Land (Japan, USA).vb...
  Applying IPS file "C:\test with spaces\Virtual Boy Wario Land (Japan, USA).vb.ips"...
   Failed: Error opening file "C:\test with spaces\Virtual Boy Wario Land (Japan, USA).vb.ips": No such file or directory
  Using module: vb(Virtual Boy)
   Loading override settings from "C:\test with spaces\mednafen-0.9.48-win64\vb.cfg"...
    Failed: Error opening file "C:\test with spaces\mednafen-0.9.48-win64\vb.cfg": No such file or directory
   Loading override settings from "C:\test with spaces\mednafen-0.9.48-win64\pgconfig\Virtual Boy Wario Land (Japan, USA).vb.cfg"...
    Failed: Error opening file "C:\test with spaces\mednafen-0.9.48-win64\pgconfig\Virtual Boy Wario Land (Japan, USA).vb.cfg": No such file or directory

   Title:     VB ﾜﾘｵﾗﾝﾄﾞ
   Game ID Code: 1245927254
   Manufacturer Code: 12592
   Version:   0
   ROM:       2048KiB
   ROM MD5:   0xfb4dc9f4ebd506702eb49e99a62bd803

   V810 Emulation Mode: Fast

  Loading custom palette from "C:\test with spaces\mednafen-0.9.48-win64\palettes\vb.pal"...
   Error: Error opening file "C:\test with spaces\mednafen-0.9.48-win64\palettes\vb.pal": No such file or directory

  Loading cheats from C:\test with spaces\mednafen-0.9.48-win64\cheats\vb.cht...
   Error opening file "C:\test with spaces\mednafen-0.9.48-win64\cheats\vb.cht": No such file or directory

 Initializing sound...
  Using "WASAPI(Shared mode)" audio driver with SexyAL's default device selection.
   Format: 16 bits(signed, 2 bytes, little-endian)
   Rate: 44100
   Channels: 2
   Buffer size: 1631 sample frames(36.984127 ms)
   Latency: 1887 sample frames(42.789116 ms)
 Initializing video...
  Video Driver: OpenGL
  Video Mode: 768 x 448 x 32 bpp
  Shader: none
  Fullscreen: No
  Special Scaler: None
  Scanlines: Off
  Destination Rectangle: X=0, Y=0, W=768, H=448
  OpenGL Implementation: Humper Chromium 2.1 Chromium 1.9
  Checking extensions:
   GL_ARB_texture_non_power_of_two found.
  Using non-power-of-2 sized textures.
  Checking maximum texture size...
   Apparently it is at least: 16384 x 16384
  Using GL_BGRA, GL_UNSIGNED_INT_8_8_8_8_REV for texture source data.
```

As you can see it is working here.
Also you can try to delete **mednaffe.ini** file to reset it.

**Comment by HoomanIsHere** [comment]
Crap. I forgot to send you the whole thing. Sorry.

Запускается Mednafen 0.9.48
 Build information:
   Compiled with gcc 4.9.4
   Running with MinGW-W64 Runtime 5.0 (alpha - rev. 0) 0000-00-00
   Compiled against zlib 1.2.8, running with zlib 1.2.8(flags=0x00000065)
   Compiled against libiconv 15.1, running with libiconv 15.1
   Compiled against SDL 1.2.15, running with SDL 1.2.15
   Running with libsndfile-1.0.28
 Base directory: C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen
 Emulation modules: nes snes gb gba pce lynx md pcfx ngp psx ss ssfplay vb wswan sms gg snes_faust pce_fast demo cdplay
 Loading settings from "C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\mednafen-09x.cfg"...
  Loaded 6110 valid settings and 0 unknown settings.
 Initializing joysticks...
  Joystick 0 - XInput Unknown Controller - Unique ID: 0000000000010000
 Loading C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\Virtual Boy Wario Land (Japan, USA).vb...
  Применение файла IPS «C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\Virtual Boy Wario Land (Japan, USA).vb.ips»...
   Failed: Error opening file "C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\Virtual Boy Wario Land (Japan, USA).vb.ips": No such file or directory
  Using module: vb(Virtual Boy)
   Loading override settings from "C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\vb.cfg"...
    Failed: Error opening file "C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\vb.cfg": No such file or directory
   Loading override settings from "C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\pgconfig\Virtual Boy Wario Land (Japan, USA).vb.cfg"...
    Failed: Error opening file "C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\pgconfig\Virtual Boy Wario Land (Japan, USA).vb.cfg": No such file or directory

   Title:     VB ﾜﾘｵﾗﾝﾄﾞ
   Game ID Code: 1245927254
   Manufacturer Code: 12592
   Version:   0
   ROM:       2048KiB
   ROM MD5:   0xfb4dc9f4ebd506702eb49e99a62bd803

   V810 Emulation Mode: Fast

  Loading custom palette from "C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\palettes\vb.pal"...
   Error: Error opening file "C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\palettes\vb.pal": No such file or directory

  Загрузка кодов из C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\cheats\vb.cht...
   Error opening file "C:\Users\Cythes\Desktop\Games and apps\Emulators\Mednafen\cheats\vb.cht": No such file or directory

 Инициализация звука...
  Using "WASAPI(Shared mode)" audio driver with SexyAL's default device selection.
   Format: 16 bits(signed, 2 bytes, little-endian)
   Rate: 48000
   Channels: 2
   Buffer size: 1776 sample frames(37.000000 ms)
   Latency: 1776 sample frames(37.000000 ms)
 Инициализация видео...
  Video Driver: OpenGL
  Видео-режим: 1366 x 768 x 32 bpp
  Shader: none
  Полный экран: Да
  Метод масштабирования: Нет
  Черезстрочность: Выкл.
  Целевой прямоугольник: X=298, Y=160, Ш=768, В=448
  Реализация OpenGL: ATI Technologies Inc. AMD Radeon(TM) R6 Graphics 4.5.13456 Compatibility Profile Context 21.19.141.0
  Проверка расширений:
   Обнаружено GL_ARB_texture_non_power_of_two.
   GL_ARB_sync found.
  Используются текстуры с размерами «non-power-of-2».
  Проверка максимального размера текстур...
   Как минимум: 16384 x 16384
  Using GL_BGRA, GL_UNSIGNED_INT_8_8_8_8_REV for texture source data.

**Comment by AmatCoder** [comment]
I don't see any error there.
Does it work if you drag&drop the rom into mednafen executable?

**Comment by HoomanIsHere** [comment]
Oh, it does! Thanks!

**Comment by AmatCoder** [comment]
Does it work now if you launch with mednaffe?

**Comment by HoomanIsHere** [comment]
If I drag and drop onto the Mednafen.exe it does work, but when I try to launch it with Mednaffe, nothing.

**Comment by AmatCoder** [comment]
Has you delete the **mednaffe.ini** file as I told you?

**Comment by HoomanIsHere** [comment]
Yeah. But nothing works.

**Comment by AmatCoder** [comment]
Are you using the last version (0.8.6)?

**Comment by HoomanIsHere** [comment]
Mhm.

**Comment by AmatCoder** [comment]
No more feedback, closing.
