### ISSUE TITLE
no 6 button conroller for PCE and Megadrive/Genesis?

### ISSUE THREAD

**Issue by ghost** [AmatCoder/mednaffe#67]
no 6 button conroller for PCE and Megadrive/Genesis?

**Comment by AmatCoder** [comment]
All input options are planned to be included but Mednaffe is being rewritten from scratch and I so it is taking me a lot of time :(

**Comment by jjfmz42015** [comment]
Oh ok! I just thought Ide mention it in case it was not noticed. I only discovered this last night.
Never used mednafen before and probably wouldnt without this nice front end.

I use to use Magic Engine for PCE but am switching to mednafen due to compatibility.
Thank you.

**Comment by jjfmz42015** [comment]
i was new to mednafen when i reported this. i have since learned you can remap controller once in mednafen and it keeps the setting.

**Comment by AmatCoder** [comment]
Added in 0.9.0 version.
