### ISSUE TITLE
"Executing mednafen failed!"

### ISSUE THREAD

**Issue by JDizzleXIV** [AmatCoder/mednaffe#68]
Hi,

When I load a ROM directly to mednafen, it launches.  Whenever I try to open a ROM for PSX in mednaffe, nothing happens and I get this in the log:

```
Executing mednafen with command line: 
"C:\Users\xxxx\Desktop\mednafen-0.9.48-win64\mednafen.exe" -psx.dbg_level "0" "D:\DiscImage\Image.cue"
Executing mednafen failed!
```

Admittedly, I have no clue what I'm doing - this is my first foray into mednafen and I was looking for a more user friendly interface.

I have mednaffe and associated files in the same folder with mednafen.  The ROM I'm trying to load is FFIX that I just ripped earlier this evening from my disc copy.

**Comment by AmatCoder** [comment]
That is weird...
Is mednafen emulator being executed as an administrator?
To check it look at the "Run This Program As An Administrator" check box (do right-click on mednafen executable-> Properties-> Compatibility)

**Comment by JDizzleXIV** [comment]
Welp.  That did it!  I set the compatibility for the mednafen executable and also ran mednafffe as administrator when I launched it.  One or both of those was the magic.  Thanks for offering guidance to a newbie :)

**Comment by AmatCoder** [comment]
Great!
But keep in mind that neither mednafen nor mednaffe require administrator privileges.
Both just must be configured to use the same standard mode.

**Comment by gunpop** [comment]
Hello everybody, i'm brazilian. Sorry anything...
I install mednaffen by repository (i use Linux Mint 19.1 Cinnamon x64)
and at last night i run games of Sega Saturn normally, and i turn of my notebook (core i3/ 6gb memory/ OS installed on a pen drive).
Today i turn on and try to play the emulator but, something the screen console menu appears, the game not load. Any help?
