### ISSUE TITLE
1.21.0-UNSTABLE

### ISSUE THREAD

**Issue by litaniast** [AmatCoder/mednaffe#69]
Mednafen was updated and changed the cfg filename to mednafen.cfg. (It loads mednafen-09x.cfg but saves new name) I think mednaffe also needs update for Mednafen.

**Comment by Asnivor** [comment]
The change to SDL2 is a big one as well. New controller config command format and new format joystick IDs.

**Comment by AmatCoder** [comment]
Work in progress on this [branch](https://github.com/AmatCoder/mednaffe/commits/0.8.x-UNSTABLE).

**Comment by Catarax** [comment]
Stable release out, after playing one time and re-opened, locked to this screen :
![screenshot_2](https://user-images.githubusercontent.com/3964507/37344558-f9858944-26ca-11e8-8122-ad3364a3b5ac.png)

**Comment by AmatCoder** [comment]
Actual version of mednaffe (0.8.6) is not compatible with 1.xx.x versions of mednafen emulator.

**Comment by ofernandofilo** [comment]
hm... the gui plays the new version, probably not complete, but after a test... to play I need to maintain the old version in the same folder, with other name - like: oldemulator.exe - and run it even without a game one time before opening the graphical interface. Then the interface opens and executes using the new emulator. But the GUI will not be reopened without first executing the old version without gui.

And yes... you can even delete the "olderemulator.exe" to be sure that it is not being used! I did not tried to changed any configuration, but maybe by luck the newer versions ran flawless every game I have.

**Comment by AmatCoder** [comment]
On Windows, Mednaffe reads **stdout.txt** file to check the version of emulator.
If you run the old version of emulator it creates a new **stdout.txt** file and then Mednaffe 'believes' that version of emulator is correct.

But Mednafe only will works as far as you don't change any settings (particularly 
all input related or video driver).

**Comment by Pcegames** [comment]
Hello, I am sorry to ask this kind of question but I was so dependent on this front end to use Mednafen that I simply can not use another one.

Do you have any estimates of when the new Mednaffe update will happen for the current version of the emulator? Thank you very much for building this front end for us.

My English is not very good and I do not practice it as much as I would like but I will improve it.

**Comment by AmatCoder** [comment]
I will try to release a new version during this weekend.

**Comment by AmatCoder** [comment]
Apologies for the delay.
Mednaffe 0.8.7 has been released with support for 1.xx.x versions of mednafen emulator.
