### ISSUE TITLE
Segfaulting immediately after launch as of fairly recently

### ISSUE THREAD

**Issue by axfelix** [AmatCoder/mednaffe#70]
Following up from some comments on the AUR package:

Mednaffe has started segfaulting for me right after it displays its own GUI briefly. Removing the config file doesn't seem to help. Here's a (probably unhelpful) basic gdb trace:

    [axfelix@nixon ~]$ gdb mednaffe    
    GNU gdb (GDB) 8.1
    Copyright (C) 2018 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-pc-linux-gnu".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>.
    Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
    For help, type "help".
    Type "apropos word" to search for commands related to "word"...
    Reading symbols from mednaffe...(no debugging symbols found)...done.
    (gdb) r
    Starting program: /usr/bin/mednaffe 
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/usr/lib/libthread_db.so.1".
    [New Thread 0x7fffedf67700 (LWP 7688)]
    [New Thread 0x7fffed766700 (LWP 7689)]
    Starting Mednaffe 0.8.6
    Mednafen 09x configuration file found.
    Mednafen version detected: 0.9.48
    ----

    Thread 1 "mednaffe" received signal SIGSEGV, Segmentation fault.
    0x00007ffff44913a0 in ?? () from /usr/lib/libpango-1.0.so.0
    (gdb) bt full
    #0  0x00007ffff44913a0 in  () at /usr/lib/libpango-1.0.so.0
    #1  0x00007ffff44973cd in pango_layout_set_attributes ()
    at /usr/lib/libpango-1.0.so.0
    #2  0x00007ffff77779a4 in  () at /usr/lib/libgtk-3.so.0
    #3  0x00007ffff777943f in gtk_scale_get_layout () at /usr/lib/libgtk-3.so.0
    #4  0x00007ffff7550478 in  () at /usr/lib/libgtk-3.so.0
    #5  0x00007ffff4beb6f1 in  () at /usr/lib/libatk-bridge-2.0.so.0
    #6  0x00007ffff66c5a60 in g_hash_table_foreach () at /usr/lib/libglib-2.0.so.0
    #7  0x00007ffff4be7575 in  () at /usr/lib/libatk-bridge-2.0.so.0
    #8  0x00007ffff4bd9142 in  () at /usr/lib/libatk-bridge-2.0.so.0
    #9  0x00007ffff094684b in  () at /usr/lib/libdbus-1.so.3
    #10 0x00007ffff0937036 in dbus_connection_dispatch ()
    at /usr/lib/libdbus-1.so.3
    #11 0x00007ffff06fe7c7 in  () at /usr/lib/libatspi.so.0
    #12 0x00007ffff66d6e38 in g_main_context_dispatch ()
    at /usr/lib/libglib-2.0.so.0
    #13 0x00007ffff66d7081 in  () at /usr/lib/libglib-2.0.so.0
    #14 0x00007ffff66d73b2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
    #15 0x00007ffff76f0eff in gtk_main () at /usr/lib/libgtk-3.so.0
    #16 0x000055555555bf9b in main ()
    (gdb) q
    A debugging session is active.
    
	Inferior 1 [process 7684] will be killed.
    
    Quit anyway? (y or n) y

**Comment by AmatCoder** [comment]
Thanks for the trace.

I'm speculating(*) but it seems that it's a gtk3 theme issue. Has you tried with another theme (i.e. Adwaita)?

(*) Segfault occurs when Pango tries set the text of a GtkScale (the value is displayed as a string next to the slider).
As this does not happen here (I'm also using Arch but with Adwaita gtk3 theme) I think that your gtk3 theme does not support some PangoAttribute (surely a font related).

**Comment by axfelix** [comment]
Still happens under Adwaita. I strongly suspect it's due to my having set Scaling Factor = 1.26 in Gnome tweaks (for DPI reasons); that's a feature they seem to often forget they have. For years it's also caused the Evince window to open slightly larger each time I run the app, like David Byrne's suit.

**Comment by axfelix** [comment]
But in this case this is at least a new (and so far Mednaffe specific) regression

**Comment by axfelix** [comment]
Oh, although! Even though it was still dying under Adwaita, I just realized I had an older version of the theme I *was* using (arc) installed from archlinuxcn and switched to the version provided by community, and Mednaffe seems good now.

Maybe I should've restarted the shell too when testing under Adwaita?

Regardless, I this this is not on your end (at worst some gtk2 methods are acting funny between recent versions of Gnome, which would not be surprising). Thanks for your patience, closing.
