### ISSUE TITLE
Mednafen version is not compatible

### ISSUE THREAD

**Issue by polsvoice** [AmatCoder/mednaffe#74]
I just compiled and installed the new Mednafen 1.21.1, but now mednaffe gives me this error when I open it:

```
Error: Mednafen version is not compatible.
You need 0.9.41 version or above.
```
I don't have any other versions of mednaffe on my computer. The Bin path in mednaffe.conf is correct.

**Comment by AmatCoder** [comment]
You must use the last version of mednaffe (0.8.7 at the time of writing). 
Previous versions are not compatible with mednafen 1.21.1.
Youcan download from [here](https://github.com/AmatCoder/mednaffe/releases/latest).

**Comment by polsvoice** [comment]
Oh, okay. I was using 0.9.0 beta.

**Comment by AmatCoder** [comment]
Yes, master branch is (practically) deprecated so most likely it will not be updated (I am rewritting Mednaffe here in a local branch).
