### ISSUE TITLE
Crash on all systems when selected some specific filters

### ISSUE THREAD

**Issue by Pcegames** [AmatCoder/mednaffe#76]
Hello firstly thank you very much for building this front end for us, in my opinion and the best there is for Mednafen.

Since the release of Mednafe 1.21.1 I noticed that when we choose some filters the emulator does not run the games, I tested all the filters and found that they are causing the emulator not to run the games if you turn them on.
There are three filters:
2xsai
Super2xsai
Supereagle
Any of those linked and Mednafe does not play any game on any of their systems.
I hope this helps in some way to improve this Front End that I like so much, thank you very much for now.

Note: My English is quite rusty but I am training, please do not take offense with some errors.

Filters Broken
![filters broken](https://user-images.githubusercontent.com/30628523/38452604-e6abb8d2-3a1d-11e8-8254-3a03cd286cef.jpg)

Filters On
![with filters](https://user-images.githubusercontent.com/30628523/38452605-e6c95838-3a1d-11e8-9411-47877b38fff1.jpg)

Filters Off
![no filters](https://user-images.githubusercontent.com/30628523/38452606-e6e72f7a-3a1d-11e8-8446-c9300f0339b2.jpg)

**Comment by Asnivor** [comment]
This happens for me as well with my own frontend as well, so its potentially a mednafen rather than frontend issue. I'll speak to the mednafen dev and find out if this is the case.

**Comment by Asnivor** [comment]
Yup, its a mednafen issue.

**Comment by AmatCoder** [comment]
Thanks to **Pcegames** for report this issue and thanks to **Asnivor** fo helping with it. Well done!

**Comment by AmatCoder** [comment]
Fixed with new mednafen (1.21.3) so closing.
