### ISSUE TITLE
Not comatible with mednafen 1.21.2-1

### ISSUE THREAD

**Issue by YangtseSu** [AmatCoder/mednaffe#78]
cfg_path = g_strconcat(home, "/.mednafen/mednafen-09x.cfg", NULL

$ ls .mednafen/
cheats  firmware  mcm  mcs  mednafen.cfg  mednafen.lck  palettes  pgconfig  sav  snaps

mednafen-09x.cfg   --->   mednafen.cfg

**Comment by YangtseSu** [comment]
After ln -s mednafen.cfg mednafen-09x.cfg
It show
Error: Mednafen version is not compatible.
You need 0.9.41 version or above.

check_version() and get_cfg() should be rewrite.

mednafen 1.21.2-1

**Comment by AmatCoder** [comment]
No more feedback, so closing.
