### ISSUE TITLE
"L2" not working using XInput controllers

### ISSUE THREAD

**Issue by Pcegames** [AmatCoder/mednaffe#80]
Hello, friend, I've probably found an issue within our favorite Front-End.

When using any XInput controller such as Logitech F530 (switching it to DInput works perfectly) or even the Xbox 360 official controller, the selected input which stands for the "L2" command just won't work.

Using the Xbox One S also proved not to wok as it should have, but it's perfectly set when pressing Ctrl + Shift + 1. That makes me think it might be a Front-End related issue.

Note: Mednafen version used is 1.21.3, but this issue comes since 0.9.xx as far as I can remember.

See attached a video where I show through Sub-Zero Mythologies game, the character should turn left when pressing LT (L2), but it won't produce any results.
https://youtu.be/dQQfawbjVYo

**Comment by AmatCoder** [comment]
Confirmed. I will fix tomorrow.

Thanks very much for the report (nice video!). And just in time :)

**Comment by AmatCoder** [comment]
Please, can you test this [updated executable](https://sites.google.com/site/amatcoder/mednaffe/downloads/mednaffe_test.zip) to confirm that the issue has been fixed?

**Comment by Pcegames** [comment]
One second

**Comment by Pcegames** [comment]
Worked perfectly!!  thanks o/

**Comment by AmatCoder** [comment]
Thanks to you for test it.
I will make a release right now.

**Comment by AmatCoder** [comment]
Fixed with 0.8.8 version released.
