### ISSUE TITLE
Cannot use bluetooth audio

### ISSUE THREAD

**Issue by pcbean207** [AmatCoder/mednaffe#83]
Emulator works great, but I can only get the audio working on my laptop's speakers. Is there any way to switch the audio source it plays on? Using Ubuntu 18.04. Thanks!

**Comment by AmatCoder** [comment]
AFAIK bluetooth audio needs PulseAudio.
And mednafen does not support PulseAudio in a direct way (only through ALSA).

[Mednafen documentation](https://mednafen.github.io/documentation/#Section_troubleshooting_nosoundlinux) states:
_[...] set the [sound.device](https://mednafen.github.io/documentation/#sound.device) setting to **"sexyal-literal-default"** to try to use PulseAudio through ALSA (assuming your distribution has things configured properly)._

You can try it although I'm not sure it will works.

**Comment by pcbean207** [comment]
That worked. Thanks for the prompt response!
