### ISSUE TITLE
Setting fullscreen stretch as default

### ISSUE THREAD

**Issue by rrooij** [AmatCoder/mednaffe#85]
In my opinion, this GUI should set the fullscreen mode to stretch while maintaining the aspect ratio. This is the default behavior in most emulators and since this GUI targets less tech savvy users than the CLI of Mednafen, I think it should be a default.

What do you think of this proposal? Or should we adhere to the defaults of Mednafen?

**Comment by AmatCoder** [comment]
Sorry but I think that we should adhere to the defaults of mednafen emulator.
