### ISSUE TITLE
Error: No mednafen configuration file found.

### ISSUE THREAD

**Issue by alebersol** [AmatCoder/mednaffe#87]
Mednafen version is 1.21.3
Starting Mednafen
Build information:
Compiled with gcc 7.3.0
Compiled against zlib 1.2.10, running with zlib 1.2.10(flags=0x000000a9)
Compiled against SDL 2.0.8(hg-11914:f1084c419f33), running with SDL 2.0.8(hg-11914:f1084c419f33)
Running with libsndfile-1.0.27
Base directory: /home/alessandro/.mednafen
Emulation modules: nes snes gb gba pce lynx md pcfx ngp psx ss ssfplay vb wswan sms gg snes_faust pce_fast demo cdplay
Opening lockfile...
Loading settings from "/home/alessandro/.mednafen/mednafen.cfg"...
Loaded 7396 valid settings and 0 unknown settings.
No command-line arguments specified.

Usage: mednafen [OPTION]... [FILE]
Please refer to the documentation for option parameters and usage.

Mednaffe message Error: No mednafen configuration file found.
Mednaffe is 0.8.8

**Comment by polsvoice** [comment]
Do you have a mednafen.cfg?

**Comment by alebersol** [comment]
Yes, in /home/~/.mednafen

But mednaffe ignores it.

The contents of the folder are as follows:

b/
cheats/
dir.txt
firmware/
mcm/
mcs/
mednafen.cfg
mednafen.lck
palettes/
pgconfig/
sav/
snaps/

Ok ?

Hope it helps.

Regards,

**Comment by AmatCoder** [comment]
Please, paste here the command output of mednaffe.

**Comment by geajack** [comment]
So, I downloaded `mednaffe-0.8.8.tar.gz`, extracted it and went into the extracted mednaffe-0.8.8 directory. I ran:

`$./configure
$make
$make install
`
`make install` gave me some error involving permissions, so I tried running it with sudo, which seemed to work. Having done that, when I now enter `mednaffe` at the command line, I get:

`Error: No mednafen configuration file found.`

in the prompt, and a dialog window showing the same message.

**Comment by AmatCoder** [comment]
Hmm, can you paste the command output from mednafen emulator?

**Comment by geajack** [comment]
```
$ mednafen "Pokemon - Gold Version (UE) [C][!].gbc"
Starting Mednafen 0.9.38.7
 Build information:
   Compiled with gcc 5.2.1 20151022
   Compiled against zlib 1.2.8, running with zlib 1.2.8(flags=0x00000055)
   Compiled against SDL 1.2.15, running with SDL 1.2.15
   Running with libsndfile-1.0.25
 Base directory: /home/jack/.mednafen
 Internal emulation modules: nes snes gb gba pce pce_fast lynx md pcfx ngp psx vb wswan sms gg cdplay demo
 External emulation modules: 
 Loading settings from "/home/jack/.mednafen/mednafen-09x.cfg"...
  Loaded 2982 valid settings and 0 unknown settings.
 Initializing joysticks...
 Loading Pokemon - Gold Version (UE) [C][!].gbc...
  Applying IPS file "./Pokemon - Gold Version (UE) [C][!].gbc.ips"...
   Failed: Error opening file "./Pokemon - Gold Version (UE) [C][!].gbc.ips": No such file or directory
  Using module: gb(GameBoy (Color))
   Loading override settings from "/home/jack/.mednafen/gb.cfg"...
    Failed: Error opening file "/home/jack/.mednafen/gb.cfg": No such file or directory
   Loading override settings from "/home/jack/.mednafen/pgconfig/Pokemon - Gold Version (UE) [C][!].gb.cfg"...
    Failed: Error opening file "/home/jack/.mednafen/pgconfig/Pokemon - Gold Version (UE) [C][!].gb.cfg": No such file or directory

   ROM:       2048KiB
   ROM CRC32: 0x6bde3c3e
   ROM MD5:   0xa6924ce1f9ad2228e1c6580779b23878
   Type:      0x10(ROM+MBC3+TIMER+RAM+BATT)
   RAM Size:  0x03(32K)
   Version:   0x00

  Loading custom palette from "/home/jack/.mednafen/palettes/gbc.pal"...
   Error: Error opening file "/home/jack/.mednafen/palettes/gbc.pal": No such file or directory

  Loading cheats from /home/jack/.mednafen/cheats/gb.cht...
   Error opening file "/home/jack/.mednafen/cheats/gb.cht": No such file or directory

 Initializing sound...
  Using "ALSA" audio driver with SexyAL's default device selection.ALSA Error: snd_pcm_open(&alsa_pcm, id ? id : "hw:0", SND_PCM_STREAM_PLAYBACK, 0) Device or resource busy
Error opening a sound device.
Initializing video...
  Video Driver: OpenGL
  Video Mode: 640 x 576 x 32 bpp
  Pixel shader: none
  Fullscreen: No
  Special Scaler: None
  Scanlines: Off
  Destination Rectangle: X=0, Y=0, W=640, H=576
  OpenGL Implementation: Intel Open Source Technology Center Mesa DRI Mobile Intel® GM45 Express Chipset x86/MMX/SSE2 2.1 Mesa 17.2.8
  Checking extensions:
   GL_ARB_texture_non_power_of_two found.
   GL_ARB_sync found.
  Using non-power-of-2 sized textures.
  Checking maximum texture size...
   Apparently it is at least: 8192 x 8192
  Using GL_BGRA, GL_UNSIGNED_INT_8_8_8_8_REV for texture source data.
```

**Comment by AmatCoder** [comment]
You are using **0.9.38.7** version of mednafen emulator.
Mednaffe 0.8.8 needs **1.21.1** or higher versions of mednafen emulator.

The last version of mednaffe that supports 0.9.38.x was [this](https://github.com/AmatCoder/mednaffe/releases/tag/v0.8).

**Comment by alebersol** [comment]
Mine is  1.21.3 and Mednaffe does not find the config file either.

I downgraded both Mednafen and Mednaffe, so, it's working. But latest version is not working as it should.

Regards,

**Comment by AmatCoder** [comment]
I can upload here a modified version to print more output and maybe it gives us a clue.

You could compile it and paste output here to help me to detect the issue.

**Comment by alebersol** [comment]
Ok, excuse me for late response, very busy this week.

Gonna get the code and make it work, so, to see what it tells us.

Regards,

**Comment by alebersol** [comment]
Nope. The link is dead, it says: A Google account for the site owner has been disabled because a violation of the Terms of Service has been identified. The site owner needs to restore their Google Account so that the site can be viewed again.

Well, you can upload to Mediafire or Mega.

Ok ?

Regards,

**Comment by AmatCoder** [comment]
It seems that Google suspended my account (!?).
Ok, bye bye Google...

I uploaded the modified code [here](http://s000.tinyupload.com/index.php?file_id=41446891871291982808). Sorry for inconvenience.

**Comment by alebersol** [comment]
Ok, gonna see that file tomorrow.

Thanks,

Regards,

**Comment by jdwininger** [comment]
The uploaded TEST source fixed the _no configuration file found_ problem for me. 
Thank you.

**Comment by alebersol** [comment]
I second jdwininger, now it works, it detected my Mednafen(1.21.3) and opened the main screen.

Gonna test the rest of it now, but, I think it will work as usual.

Regards,

**Comment by alebersol** [comment]
Ok, did test it against my Mednafen 1.21.3 and it works great, as it always did.

I sent to my distro the rebuilt package, with your new sources, so to update the package in our repos.

Thanks for your response, you rock!

Regards,

Ps.: Can close this one, solved.

**Comment by AmatCoder** [comment]
Hmm, one moment...
Those test sources do not have significant changes. It just print a few variables to console output.
Does test version work fine but normal version 0.8.8 does not?

**Comment by alebersol** [comment]
Exactly! The normal 0.8.8 dos not find Mednafen, but this test version worked great, as it has always been in past versions.

**Comment by AmatCoder** [comment]
Did version 0.8.7 work well for you?

**Comment by alebersol** [comment]
I skipped that version, jumped from 0.8.6 to 0.8.8

**Comment by AmatCoder** [comment]
The only relevant change was [this](https://github.com/AmatCoder/mednaffe/commit/0f05465fad686f8aceeaf9da7a1845ce81c07392).

Are you using MEDNAFEN_HOME environment variable? (You can look it with the command `printenv`.)

Did you get any warning when compiling 0.8.8?
Also, what is your distro?

**Comment by alebersol** [comment]
No, it doesn't use the MEDNAFEN_HOME variable.

I got no warning when I compiled the 0.8.8

My distro is PCLinuxOS.

Ok ?

Regards,

**Comment by AmatCoder** [comment]
Well, I think that I see the problem...

You did not compile and use _normal_ mednaffe 0.8.8.

You are complaining about a RPM package from PCLinuxOS.
This package is wrong because somebody built an old version from master and packed it as '_mednaffe-0.8.8-1pclos2018.x86_64.rpm_'. **But is not 0.8.8 version**.

The official releases are [here](https://github.com/AmatCoder/mednaffe/releases). To create a package must use these files.

**Comment by alebersol** [comment]
Oh, Ok then. Could be the prior version was not 100% Ok ? It's me who packages for PCLOS these packages (Mednafen and Mednaffe). And, yes, I might have gotten the wrong package, since I do a lot of packaging. But, it's all good now. Can close this one as solved.

**Comment by ShneekeyTheLost** [comment]
I am having a similar issue, but I downloaded directly from this github. Running Linux Mint. Does not seem to have a MEDNAFEN_HOME environment variable when I use `printenv`. The mednafen directory is simply $HOME/.mednafen so I don't see how it should be a major problem to find it. 

Tempted to add the environment variable manually.
