### ISSUE TITLE
How does the netplay tab work

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [AmatCoder/mednaffe#91]

**Comment by AmatCoder** [comment]
[Mednafen Netplay Documentation.](https://mednafen.github.io/documentation/netplay.html)

Also you can read [this](https://forum.fobby.net/index.php?t=msg&goto=4650&).

**Comment by CindyLouWho03** [comment]
Let me share more info and clarify. I know how medafen net play works. What I don't know is your net play tab in the GUIs settings. It seems to have no use, but I'm like why have it if it doesn't work. Am I missing something

**Comment by AmatCoder** [comment]
Netplay options into mednaffe let you to change default values (like server, port, password etc.)

Yes, you also can change those into network play console if you mean to this.

**Comment by AmatCoder** [comment]
Or maybe you mean that it does not connect automatically to server.
You must press "T" key and write '/server' into network play console.

**Comment by CindyLouWho03** [comment]
Ahh, its fine for what im trying to do, but it might be interesting if you could make a GUI that can hook into the it. By showing ping and a GUI interface
