### ISSUE TITLE
light gun in sega saturn

### ISSUE THREAD

**Issue by altlyser** [AmatCoder/mednaffe#93]
Hello. how to enable lightgun support? In Mednaffe - Virtua Cop 2.

**Comment by AmatCoder** [comment]
You can't enable lightgun with last mednaffe (0.8.8)
But next version (0.9.0) will allow it.

**Comment by altlyser** [comment]
wow, thanks!

**Comment by AmatCoder** [comment]
Added in 0.9.0 version.
