### ISSUE TITLE
No configuration file found

### ISSUE THREAD

**Issue by theelectricdave** [AmatCoder/mednaffe#95]
regardless of what is specified at the command line, i get a configuration file not found error. I also tried launching with sudo.

The executable is compiled from source per the instructions in readme, on ubuntu 18.04 64 bit.

Command line output:

`neptronix@trash80:~/Desktop/mednaffe-0.8.8$ sudo mednaffe

(mednaffe:16496): IBUS-WARNING **: 19:50:35.060: The owner of /home/neptronix/.config/ibus/bus is not root!
Error: No mednafen configuration file found.`

**Comment by AmatCoder** [comment]
As it says in the Readme:

> Note: Mednaffe only works with 1.21.1 or higher versions of mednafen emulator.

Most probably you have installed mednafen emulator from ubuntu repositories. On ubuntu 18.04, 
mednafen 0.9.48 is packed. Then you can:

- Use mednaffe from ubuntu repositories (version 0.8.4).
- or compile a newer version of mednafen emulator.

And do not launch mednaffe or mednafen with `sudo`.

**Comment by AmatCoder** [comment]
No more feedback, closing.
