### ISSUE TITLE
Compilation error: joystick.h

### ISSUE THREAD

**Issue by polsvoice** [AmatCoder/mednaffe#97]
I'm getting this error when I try to compile:
```
widgets/medlistjoy.c:25:10: fatal error: joystick.h: No such file or directory
 #include "joystick.h"
          ^~~~~~~~~~~~
compilation terminated.
```
I assume I'm missing a library somewhere.

**Comment by AmatCoder** [comment]
No, it was my fault. I forgot to upload some files... :(
Fixed with commit 7a020f4.
Thanks for reporting!
