### ISSUE TITLE
Trying to compile for windows google drive link is password protected

### ISSUE THREAD

**Issue by CrankySupertoon** [AmatCoder/mednaffe#98]
https://drive.google.com/file/d/1MJMWTGMBMsCpn_SuCKlHCimvt6vhYNgt/view?usp=sharing

**Comment by CrankySupertoon** [comment]
![image](https://user-images.githubusercontent.com/48419040/61005419-27096780-a336-11e9-902f-8df68de0d248.png)

**Comment by AmatCoder** [comment]
It is not password protected, Google just suspended my account... :(

Are you interested in compiling 0.8.8 version or master branch?

**Comment by CrankySupertoon** [comment]
Master if possible but I’ll compile whatever

**Comment by CrankySupertoon** [comment]
@AmatCoder

**Comment by AmatCoder** [comment]
Sorry for late reply.
Last days I could not login in GitHub because the account suspended was my primary email and now they send a verification code to that email. :(

**Comment by AmatCoder** [comment]
Continuing with the issue, the deleted file was for cross-compiling (it makes a Windows exe from a Linux OS) not for compiling from Windows.

What operating system are you using?

**Comment by CrankySupertoon** [comment]
Windows 10

**Comment by CrankySupertoon** [comment]
Update?

**Comment by AmatCoder** [comment]
If you want to compile a Windows executable from master branch then you just need to use the [MSYS2](https://www.msys2.org/) toolchain.

No need for [mxe-mednaffe-0.8.8.tar.xz](https://github.com/AmatCoder/mednaffe/blob/wiki/CrossCompileToWindows.md) archive.

**Comment by CrankySupertoon** [comment]
Do I just feed it the cmake script?
