### ISSUE TITLE
Distribute Mednaffe in a Flatpak

### ISSUE THREAD

**Issue by LeandroStanger** [AmatCoder/mednaffe#99]
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by AmatCoder** [comment]
I am interested in this but I am waiting to release a final version.

Also, a flatpak package has to include the emulator so I would need permission from mednafen authors.

**Comment by Pobega** [comment]
Considering Mednafen is GPLv2 (according to https://mednafen.github.io/) do we actually need permission? If there's still interest in this I can attempt to work on it.

**Comment by AmatCoder** [comment]
Just it is a matter of courtesy, not license. As stated in [App Submission Guide](https://github.com/flathub/flathub/wiki/App-Submission):

> Flathub is primarily intended as a service that is used by app developers to distribute their apps. Our goal is to give developers control of their apps and to allow them a closer relationship with their users without middlemen getting in the way. [...] We would prefer that these applications are controlled by their authors. [...]

> **There’s an app that I’d like to see on Flathub, but I’m not the developer**
> 
> If there’s an app that you'd like to be distributed on Flathub, the best first course of action is to approach the app’s developers and ask them to submit it. [...]

Developers of mednafen emulator may prefer to distribute their application or not to be distributed alongside a front-end.

**Comment by anthonyajumelles** [comment]
Definitely respect the mindset but Mednaffe is already automatically packaged with Mednafen on several distros. None of the devs have ever objected to that.

**Comment by AmatCoder** [comment]
Work in progress here: https://github.com/flathub/flathub/pull/2346

**Comment by AmatCoder** [comment]
Flatpak is already available on [Flathub](https://flathub.org/apps/details/com.github.AmatCoder.mednaffe).
Repository is [here](https://github.com/flathub/com.github.AmatCoder.mednaffe).

Thanks to @GabMus for the help with this!
